UKHomeOffice/asl-pages

pages/common/assets/sass/_datatable.scss

text-indent only applies to the first line of text, so multiline restrictions end up looking out of whack.

Use margins instead of text-indent

---

lib/page.js
pages/common/content/index.js
pages/common/views/components/link.jsx
pages/common/views/containers/link.jsx
pages/establishment/dashboard/content/index.js
pages/establishment/dashboard/tests/index.js
pages/establishment/dashboard/views/index.jsx
pages/establishment/details/views/index.jsx
pages/establishment/list/views/index.jsx
pages/place/list/views/index.jsx
pages/place/read/index.js
pages/place/read/views/index.jsx
pages/profile/list/views/index.jsx
pages/profile/view/tests/middleware.js
pages/project/list/views/index.jsx
test/functional/app/index.js
test/functional/fixtures/index.js
test/functional/fixtures/profile.json

Instead of assuming a common url pattern across all implementations, use a url map passed to the parent app (and exposed on `res.locals.static.urls`) to go from a page key (which correspond to the folder/router structure exposed by this module) and optional parameters to build urls.
Also maps the page title content snippets to use the same structure as everything else in order to make the establishment dashboard work nicely.

Use url configuration for link elements

---

package-lock.json
package.json
pages/common/views/components/form.jsx
pages/common/views/components/snippet.jsx
pages/common/views/containers/form.jsx
pages/place/delete/views/index.jsx
pages/place/update/views/confirm.jsx

* updated govuk-react-components to 1.1.0 - this includes support for elements as label, error and hint props
* use correct exported TextArea in delete view

Fix react PropType warnings

---

pages/common/views/containers/datatable.jsx

This will hide columns in datatables if no row in the entire dataset has a value in that field.
For example, we won't put the "area" column in the schedule of premises if no single row in the dataset (unfiltered) has an area defined.

Make column headings dynamic

---

pages/place/formatters/index.jsx
pages/place/list/views/index.jsx

If we are viewing a diff of changes we don't want to include a link to the NACWO profile - this is because the user is in an edit journey

Removed NACWO link in diff table

---

pages/common/views/components/filter-table.jsx

They don't work, they can go back again when/if they do work or there are requirements.

Remove export links from tables

---

pages/common/views/components/datatable.jsx
pages/common/views/containers/datatable.jsx

While a datatable component is in a loading state then add a class to the top-level `<table>` component to indicate this fact.
Note that no styles have been bound to this class yet.

Add a "loading" class to tables that are being refreshed

---

lib/reducers/pagination.js

We want to go back to page 1 (or 0) when we filter an existing data table. Otherwise weird things happen like we say we're showing 21-5 of 5 records.

Reset pagination state when changing filters

---

pages/common/views/components/pagination.jsx
test/functional/fixtures/index.js
test/unit/views/components/pagination.spec.jsx

When going past page 3 the page numbers in the control should show the current page with 2 pages either side. Previously only pages 1-5 were ever shown.

Fix bug with pagination control page numbers

---

pages/common/views/layouts/default.jsx

The user menu requires a redux provider to render, which is not applied in error pages. Pass an empty user object to the status bar in the case where an error page is rendered.

Prevent status bar trying to load user on error pages

---

package-lock.json
package.json
pages/place/create/index.js
pages/place/update/index.js
test/unit/pages/place/routers/create.spec.js
test/unit/pages/place/routers/update.spec.js

The declaration property is not used downstream anywhere, so there's no point in sending it. Especially given that it causes API json schema validation to fail.

Omit `declaration` property from API submissions

---

pages/common/views/components/snippet.jsx
test/unit/views/components/snippet.spec.jsx

Trims any leading whitespace from multiline content
Allows wrapper nodes in cases where the wrapper node is not the _only_ <p> tag - i.e. in cases where it's not a single-line string.

Fix markdown rendering in snippet components

---

pages/common/assets/sass/style.scss

Links styled as buttons in dashboard list items were disappearing when clicked do to focus styling inherited from the links.

AS-679: Exclude buttons from link focus styling

---

lib/page.js

Some users obtain permissions based on global properties (i.e. inspectors and other ASRU users) so ensure the client has access to all the actions a user can carry out, and not just those inherited from an establishment.

Expose all allowed actions to client

---

lib/middleware/permissions.js

We effectively have two functions at the moment which perform the exact same action in two different ways. Standardise on one of those.

Use `req.user.can` for determining permissions in middleware

---

pages/pil/certificate/schema/index.js

An accessor should only be specified for a form field when the value in the model is an object.
For string values, just omit the accessor.

AS-666: defining an accessor when value is not object breaks the select input

---

package-lock.json
pages/pil/application/index.js
pages/pil/application/views/procedure-data.jsx
pages/pil/index.js
pages/pil/procedures/index.js
pages/profile/index.js

We now create an empty PIL record in the db when the user selects the category of PIL to start the application process.
Procedures are stored against the PIL record.

AS-687: Persist procedures against PIL

---

pages/pil/categories/index.js
pages/pil/categories/views/index.jsx

The links were using the currently signed in profile id rather than the profile id in the url.

AS-732: use correct profile for PIL links

---

pages/common/views/components/link.jsx

We can't do anything later if it's not a string, and there's misconfiguration cases where it can easily resolve to a "not string" that currently throw an opaque error - "href.split is not a function"

Check link is a string instead of only truthiness

---

pages/common/views/components/status-bar.jsx

There are some error cases - missing session store or failed auth - where the user isn't defined at all, and so errors are swallowed by "cannot read property 'profile' of undefined".

Allow error pages to render if no user is defined

---

pages/pil/update/views/index.jsx

This is just used to easier identify sections in functional tests

forgot to commit this

---

lib/page.js

In particular, pages in the register service, where a user session has not been created. These currently crash with an error on this code.

Support pages which don't have a logged-in user

---

lib/middleware/route-builder.js
pages/place/create/index.js
pages/place/delete/index.js
pages/place/update/index.js

The wrong parameters are being passed in some cases to the url builder, which means pages are 404-ing.

Fix redirect url parameters

---

pages/common/routers/task-list.js

The data access by direct property access is really fragile when it meets data that doesn't quite fit expectations, which is what's making pre-prod be really crash-y.
Instead use `lodash.get` to that it doesn't fall over quite so hard if the data it finds doesn't match the expected form.

Ensure backwards compatibility when accessing properties

---

lib/page.js
package-lock.json
package.json
pages/common/content/index.js
pages/establishment/details/index.js
pages/feedback/index.js
pages/pil/index.js
pages/pil/update/index.js
pages/place/index.js
pages/profile/index.js
pages/profile/invite/index.js
pages/profile/read/index.js
pages/project/list/index.js
pages/user/account/views/index.jsx
pages/user/index.js
pages/user/update/index.js

This allows each page - or set of nested pages - to push their own breadcrumb elements onto the stack.
Also removed some inline requires and pull them to the top of files.
This doesn't touch any of the PIL bread-crumbing at the moment, because it's a bit of a Balrog. There needs to be some work around how and if we expose the owner of the PIL in the UI, because it currently isn't displayed, which is probably bad.

Add breadcrumbs to pages

---

pages/profile/invitations/index.js
pages/profile/invite/index.js

Redirect to the list of open invitations after inviting a new user. Sort the table by `createdAt` with newest to the top so that the new invitation is visible at the top of the list.

Redirect to invitations list following invite

---

package-lock.json
package.json
pages/place/list/views/index.jsx
pages/place/list/views/row.jsx

Apply a filter on `place.update` permissions when showing the edit controls on a row of the schedule of premises.

Hide edit controls for non-admin users

---

pages/common/helpers/index.js
pages/place/formatters/index.jsx
pages/place/schema/index.js

The profile id is the data point we eventually want in the database, so make sure we're using that in the forms where we edit places in the schedule of premises.

Load NACWOs in places amendment forms by profile id

---

pages/pil/read/content/index.js
pages/profile/roles/content/confirm.js
pages/profile/roles/content/index.js
pages/profile/roles/content/success.js

`merge` will mutate the object provided as the first argument, so passing a common content object as the first argument causes the common content to be overwritten with the custom content, and can lead to incorrect content being displayed in other situations.
Instead pass an empty object as a first argument to create a new content object.

Prevent mutating common content when extending

---

pages/task/list/content/index.js
pages/task/list/views/tasklist.jsx

Model types don't map one-to-one to licence types, most are PEL.
Add more action types to content file. This is not complete, more are coming, but I think it covers everything that's possible in system today.

Improve content in task list pages

---

package-lock.json
package.json
pages/task/read/content/pil.js
pages/task/read/index.js

If the NTCO cannot view all profiles at an establishment then they will not be able to endorse PILs for non-named users.
We should make this obvious using a different error message.

Display a different error message if the NTCO does not have profile read perms

---

lib/utils/index.js
pages/task/read/content/base.js
pages/task/read/content/confirm.js
pages/task/read/content/pil.js
pages/task/read/content/success.js
pages/task/read/index.js
pages/task/read/routers/confirm.js
pages/task/read/views/confirm.jsx
pages/task/read/views/index.jsx
pages/task/read/views/pil.jsx
pages/task/read/views/playback.jsx
pages/task/read/views/success.jsx
pages/task/schema/index.js

The content of the task modules was hard-coded to a lot of PIL content, which is not relevant to other tasks.
Refactor away the PIL specific content and provide fallbacks for a generic task.
Determine the available options from the output of the workflow API, and not locally defined content, with default content values provided for the available statuses.
Moves reason field out of a conditional reveal and allows a comment to be input for all decisions, only marking it mandatory for certain decisions.

Refactor task display to decouple from PIL endorsement

---

pages/task/list/router.js

This is required to expose the progress parameter to the xhr requests which load paginated data.

Include progress param in datatable store

---

pages/place/create/content/index.js
pages/place/routers/confirm.js

If you tick the declaration on the places confirm page, and then come back to it, it was attempting to render the declaration in the ModelSummary.

Remove declaration field in places summary

---

pages/pil/training/routers/modules.js
pages/pil/training/views/modules.jsx
pages/pil/update/views/index.jsx

This does some early validation before submitting to the API for modules that require species.
https://github.com/UKHomeOffice/asl-schema/pull/134 should be merged, and then `asl-public-api` updated first.

Allow modules with no species fix

---

lib/utils/index.js
package-lock.json
package.json
pages/pil/training/views/modules.jsx

The ids being passed to the species selector were previously non-unique and contained whitespace and other non-alphanumeric characters. This made the labels not correspond to the correct elements, and id selectors impossible to use in integration testing.

Fix id properties in species selection

---

pages/task/list/content/index.js

This might not be needed depending on the outcome of https://jira.digital.homeoffice.gov.uk/browse/AS-962

Add missing ntco-endorsed status

---

pages/task/read/views/success.jsx

This is currently flawed as it does not represent a full picture of the workflow, so can only be shown in certain circumstances (i.e. it makes no sense for an inspector as it doesn't show their actions) and is hard-coded to "Endorsed" so doesn't make sense for granting licences either.
Remove until a version that scales across all tasks and states is available.

Remove progress indicator from task success screen

---

pages/profile/read/views/profile.jsx

React was moaning about not being allowed to render a `<form>` inside a `<p>`. Fixing this by reversing the order resolved the weird href values being inserted into links elsewhere.
I have no idea why.

Move p tag to inside form

---

pages/profile/read/views/index.jsx

React complains about invalid dom nesting, and sets link hrefs to the wrong values when it throws errors.

Remove `<p>` tag wrapping `<h1>` on profile page

---

pages/task/read/views/pil.jsx

These were moved, but without moving the lookup in all instances

Fix content lookup path for procedure definitions

---

pages/task/read/views/role.jsx

It was looking for `comments` but the field is `comment`

Fix comment lookup on named role task review

---

pages/task/read/views/confirm.jsx

This wasn't actually submitting the forms before so no tasks could be progressed.

Add type=submit to task confirm page buttons

---

pages/task/read/views/confirm.jsx

We need the children here to be rendered inside the form tag so that the button can submit the form. Using the `FormLayout` component prevent this without making potentially breaking changes to the upstream components.
Instead add the two divs that are provided by the `FormLayout` component here and use the `Form` component directly.

Remove FormLayout component from task confirm screen

---

pages/profile/roles/remove/index.js
pages/profile/roles/remove/schema/index.js

Previously the form to add a named role POSTed a `role` of the role type, but removing POSTed the role id.
This meant that shared code on the confirmation page failed to find the expansion text for the role because it was trying to find it from a database uuid and not a role identifier.
Instead use the type in all cases, and lookup the corresponding database uuid from the profile roles when submitting a removal request to the API.

Use role type as the POSTed value consistently in managing named roles

---

pages/establishment/details/views/index.jsx

* Use markdown rendering for custom conditions which can be multiple paragraphs in data
* Only show rehoming and killing authorisations sections if there's actually content to be displayed

Fix bugs in establishment details page

---

pages/task/read/views/pil.jsx

If `profile.exemptions` is falsy then don't try to read its length.

Prevent profiles with no exemptions throwing error on PIL application

---

pages/task/read/views/index.jsx

Fixes AS-1104 - "submitted by" has a broken profile link on task review pages

profile.view link requires establishment id

---

pages/place/schema/declarations.js

Trying to load a label for the declarations in the model summary component fails because none is defined, but declarations shouldn't be in the model summary anyway.

Do not show declarations content in ModelSummary

---

pages/profile/roles/remove/content/index.js
pages/profile/roles/remove/index.js
pages/profile/roles/remove/schema/index.js
pages/profile/roles/views/confirm.jsx

One was using a field name of `role` and the other a field name of `type`. Standardise on `type` because that's what the field is called in the database.

Standardise add and remove named role journeys

---

pages/task/list/router.js

When a user is requesting their homepage with a "my tasks" tab then the tab was selecting, but the API request was defaulting to "outstanding". Instead explicitly default to the first tab available if none is provided by the query string.

Request correct task list

---

pages/task/read/views/pil.jsx

This is throwing an error for some tasks becuase the procedures doesn't exist.
Also standardises the checks on array lengths - some were using `!!` and others using `> 0` to check the same thing.

Check procedures exists before reading length

---

pages/project-version/middleware/index.js

When finding paths from the current version data in a previous version it is possible that the path does not exist, and if this is the case then currently an error is thrown.
Instead check each fragment of the path is available before attempting to traverse down, and if any segment is undefined then return early with no value.

Protect against undefined paths in project data lookup

---

pages/profile/roles/apply/content/index.js
pages/profile/roles/remove/content/index.js

The role field was keyed incorrectly when defining the messages so the page threw instead of showing a message.

Fix validation messages on named roles

---

pages/place/formatters/index.jsx

It's possible to have a place with no NACWO, which throws at the moment because the no NACWO doesn't have a name. Instead check the NACWO exists before trying to read their name.

Check NACWO exists before trying to format it

---

pages/project/content/index.js
pages/project/list/views/index.jsx

Otherwise there's no way for a user to see revoked projects.

Add a revoked tab to establishment project list page

---

pages/profile/list/index.js
pages/profile/list/views/index.jsx

When showing PIL numbers and licence holder roles, make sure the licences are active.

Only show active licences in people list

---

pages/profile/read/content/index.js
pages/profile/read/views/profile.jsx

The default text for noDob, under18, and addDob have been changed.
I have removed the 'Can't apply for licence' heading.
Note that the logic here needs changing. The only time that 'None' would display in this component is if a user has a DoB in their account, is over 18, but has not yet applied for a PIL. In all other cases, 'None' should be omitted.

Changes to inline states

---

pages/profile/invite/index.js

This functionality has been extended to ASRU users, which means the establishment cannot be loaded from the users profile as it does not exist there for ASRU users.
Instead make an API call to load the establishment data.

Use API call to load establishment data on invite page

---

pages/task/read/content/base.js

Anything else can wait.
I assume this changes the heading in the left-hand nav AND the page body on task review pages.
This currently only appears on amendments, but we may need to have alternate versions when revocations, suspensions etc become things.

Last change before go live

---

pages/task/read/views/profile.jsx

If a user has no current date of birth then the date format function renders "1st january 1970". Instead it should render a `-`.

Render null dates correctly on profile update tasks

---

pages/place/schema/index.js

ASRU want to be able to edit restrictions on places, but because none of them have NACWOs they can't do it because they're not able to assign NACWOs.
Un-require NACWO to be set in order to allow ASRU to edit.

Don't require NACWO to be defined on a place amendment

---

pages/place/schema/index.js

`schema.nacwo.validate` is undefined so was throwing an error.
The `definedValues` validator needs to allow no value being set.

Fix NACWO validation

---

pages/common/components/in-progress-warning.jsx
pages/common/routers/datatable.js
pages/task/list/content/index.js
pages/task/list/router.js
pages/task/list/views/index.jsx
pages/task/list/views/tasklist-unavailable.jsx
pages/task/list/views/tasklist.jsx

If workflow is unavailable the api now still responds but with a connectionError if trying to load all tasks, and a single task with action: 'failed' when fetching open tasks for a model.
Handle these cases by showing an alternate component for the tasklist and different message when trying to edit a model

Handle workflow connection errors

---

pages/task/index.js
pages/task/read/routers/confirm.js
pages/task/read/routers/success.js

We were not clearing session on task success, so the next time around status and comments were being persisted.
Added redirect to confirm page - users should not be able to visit this page once the task has been actioned

Clear session on task success

---

pages/project-version/docx/index.js

We were deconstructing the project into three `const`s and then rebuilding an object from those properties. We can just pass the object straight through.

Simplify project parameters

---

pages/project-version/read/index.js

If an open task does not exist then this condition throws. This means ASRU users cannot currently view granted PPLs.

Fix ASRU users viewing granted PPLs

---

pages/common/routers/datatable.js

If an internal user has sorted their task list then the query string will contain the sort fields. If they then search then the task list sort order tries to apply to the establishment search and fails because it's sorting a column that doesn't exist.
Check it exists first.

Check sort column exists in schema before trying to apply

---

pages/task/read/middleware/update-data.js

The mapping of grant action to update was only meant to apply to PILs but it was also mapping project grant actions, which meant the condition further down the file was being missed and projects were redirecting incorrectly.
Move the mapping for not-projects into an else-if so that projects are handled correctly.

Don't rewrite task actions on project grant

---

pages/task/list/views/tasklist.jsx

This allows for disambiguation between multiple PPL tasks where the PPL holder is the same. Specifically in automated tests.

Add project title as a title attribute to project tasks

---

pages/project-version/middleware/index.js

Because other comparison functions return a set of granted and latest changes even when the two are the same then the downstream consumer always expects the `latest` value to exist, and so when it's not returned it is still rendered, but as "No answer provided" because the value isn't sent.
Instead always return both granted and latest values, but also the version ids that those resolve to, so that downstream implementation can decide how best to deal with the case where those are the same.

Include version ids on response from field versions endpoint

---

pages/project-version/middleware/index.js

It's not async, so never return a promise.

Make sure function always returns an array

---

pages/profile/invitations/schema/index.js
pages/profile/invitations/views/index.jsx

Is re-issuing an invitation then the original invitation is updated, so the timestamp in the table needs to show the re-issue date not the original date.

Use updated at instead of created at timestamp for invitation list

---

pages/profile/invitations/index.js

Table should be sorted by updatedAt not createdAt by default.

Set default sort order on invitations list

---

pages/project-version/lib/extract-comments.js

This is needed on the client to determine if a comment can be edited or not.

Expose comment ownership on comments

---

pages/task/read/views/components/activity-log.jsx

* Resubmitted events should include a link to the submitted version

Bugfix - show version on resubmitted events

---

pages/project/read/views/index.jsx

The task type is currently stored before revocations are processed so revocations end up being incorrectly described as amendments.
Move the revocation case to before the type is mapped onto status.

Handle revocations as well as applications and amendments

---

pages/task/list/content/index.js
pages/task/list/views/tasklist.jsx

If there are no tasks to show (before filters are applied) then instead of taking up space with filters, filter summary and an empty table, simply show a "no tasks" message instead.

Hide task list and filters when there are no tasks

---

pages/pil/read/views/index.jsx

This might just be wonky seed data, but the categories don't always display in the correct (alphabetical) order. Sort them before rendering to make sure they're always sensibly ordered.

Make sure PIL categories are rendered in order

---

pages/common/content/success-messages.js

Content loading is dynamic and dependent on status, so needed content for `awaiting-endorsement`.

Add content for PIL amendment submission

---

lib/middleware/permissions.js

If a user does not have permission to perform a task then the correct error code is a 403 - which is consistent with the response codes sent by the API layers.

Respond with correct error code in permissions middleware

---

pages/project-version/middleware/index.js

The actual bug manifested by this is where an array contains `null`, which technically should not be possible, however we should not always try and access id from the entry as sometimes we may actually wand falsy entries.

Bugfix - protect against falsy array entries

---

pages/common/routers/datatable.js

The redirect wasn't preventing the middleware chain from further execution, so would throw an error about sending headers after a response was sent in those cases.
Instead make sure that if the redirect applies then the middleware chain does not continue to execute.

Only send one response in datatable normalisation redirect

---

pages/pil/procedures/index.js
pages/pil/species/index.js

Because `lodash#merge` performs a deep merge of the old values and the new it's not possible to remove procedures or species from a PIL application.
Instead do a shallow merge so that array values are completely replaced by the new values.

Shallow merge PIL procedures and species

---

pages/project-version/pdf/index.jsx

If a user downloads a PDF of a freshly created project then lots of things fail because the project is `null`. Give it a default value with a default title if the project is completely untouched.

Support PDF rendering of null projects

---

pages/task/read/routers/success.js

If no status can be determined from the session then redirect the success page back to the task screen. Otherwise errors are thrown later in the middleware pipeline.
Copies [the equivalent code in the confirm router](https://github.com/UKHomeOffice/asl-pages/blob/master/pages/task/read/routers/confirm.js#L12-L14).

Redirect task success pages if session has expired

---

pages/task/read/content/base.js

The old content doesn't make any sense for people who have options other than approve or reject.

Improve error message when no task option selected

---

pages/pil/procedures/index.js

If a person takes a while completing the procedures part of a PIL application then they can end up losing the values from the top-level PIL application on the session. If that happens then don't throw, just save the current procedures and continue.

Don't assume top-level session exists

---

pages/project/routes.js

`req.project` doesn't exist for imports, so the checking of `req.project.licenceHolderId` fails with an error.

Fix permissions check for import route

---

pages/project/index.js

Currently this attempts to do a db lookup but fails because the id is not a UUID. Catch that case early and respond with a 404 instead of a 500.

Throw a 404 error for malformed project id

---

pages/task/read/routers/confirm.js
pages/task/schema/confirm.js

If a task is being set to a status which it is already at then simply redirect back to the task page.
It seems like licensing officers are making multiple near-simultaneous requests, either through multiple rapid-fire clicks, or refreshing if there's latency. This eventually results in an error on the subsequent requests. Instead handle it gracefully and return them to their processed task.

Handle double posts to task updates

---

pages/project-version/index.js

These are misconfigured to 100kb and not the 5mb that they should be.

Fix payload size limits for projects versions

---

pages/project-version/docx/index.js

Default the project data to `{}` if it is null.

Allow downloading word documents of empty projects

---

pages/pil/dashboard/index.js
pages/task/read/middleware/update-data.js

PILs are only editable at the establishment that owns them, so send the user to the correct establishment.
This will mean that admins on the receiving side still won't be able to edit a PIL transfer in progress, but at least the applicant will be able to.

PILs are still owned by the original establishment until transfer is approved

---

pages/pil/procedures/index.js
pages/pil/species/index.js

* These were using req.pil as a base, which is not hydrated from task data on a task update.
* Use req.model instead which is updated correctly

Bugfix - hydrate procedures and species

---

pages/establishment/update/routers/confirm.js
pages/place/routers/confirm.js
pages/role/routers/confirm.js

Move this into the `configure` method on the form so that all form-related operations are encapsulated into the context of the form router itself and not dependent on prior middleware.

Refactor requiresDeclaration definition

---

pages/role/apply/index.js

The redirect if a user's session expires currently tries to redirect to `role.undefined` because it uses the `action` param, which wasn't being passed.
I think the `type` is no longer relevant, or at least I can't see where it is used.

Fix redirect in checkSession middleware on role.create

---

pages/common/routers/form.js
test/unit/routers/form.spec.js

The `getValue` functions are being invoked for "pseudo" form fields even when there is no session data present because the session is initialised with a value of `{}` which is always truthy.
Instead check that the session is non-empty before extending the model values with any session values.

Don't overwrite pseudo form fields with empty session data

---

pages/pil/training/routers/certificate.js

The validation errors should be cleared from the certificate form (i.e. `req.model/id`) and not the top-level PIL.

Delete correct values from form session on certificate post

---

pages/project-version/docx/index.js

* `application` was intended to be store.application, not req.project - however the docx renderer has been amended to consume the latter.
* Added establishment to be used in renderer

Bugfix - pass est details to word renderer

---

pages/pil/read/content/index.js
pages/pil/read/schema/index.js
pages/pil/read/views/index.jsx

Hide the same field on revoked PILs because it wouldn't make any sense to display it.

Add review dates to PIL pages

---

pages/pil/exemptions/routers/exempt.js
pages/pil/procedures/index.js
pages/pil/species/index.js
pages/pil/training/routers/exempt.js

The validation errors are scoped under the `model` id, not the PIL id.

Fix incorrect session scope

---

pages/establishment/pdf/index.jsx
pages/pil/pdf/index.jsx
pages/project-version/pdf/index.jsx

Continue to throw 500 errors on the client, as _all_ PDF should render correctly, but include downstream error status in message to allow easier debugging.

Surface error status on PDF generator errors

---

pages/common/routers/datatable.js

This is now stored in redux under the datatable property, so needs to be exposed in locals there too.

Export datatable schema in locals

---

pages/establishment/licence-fees/overview/views/index.jsx

This could be the configured fee or it could be zero depending on whether or not the PEL was active during the billing period.

Show value from API for PEL fee

---

pages/establishment/licence-fees/index.js

It wasn't actually calling the `next` function before so would just hang on an error.

Fix error handler for billing redirect

---

pages/establishment/licence-fees/index.js

If all the request is asking for is a new set of table data via XHR then don't make the additional API request to get the global totals as they will not be used.

Skip API request for global billing metadata if XHR request detected

---

lib/validation/validators.js
pages/pil/training/schema/certificate.js
pages/user/update/schema/index.js
test/unit/validation/validators.spec.js

Defining the date in the schema only allows for a fixed date to be used for validation, and not one that is relative to the current time. Add support for comparison date functions in validators so that dates relative to the current date can be used.
Additionally add support for a `'now'` shortcut to the current date.

Support dynamic and placeholder dates in date validation functions

---

pages/task/read/views/components/activity-log.jsx

If a task has no establishment id associated with it then make any links within the activity log go to a global profile rather than an estabishment scoped one.

Fix links to profiles in tasks with no establishments

---

pages/task/list/content/index.js

Override the default content used for project expiry with specific content for PPL review deadlines.

Update content for PPL deadline expiry in task lists

---

pages/common/assets/sass/style.scss
pages/task/read/views/models/index.jsx

If the user was just ASRU admin and didn't have LO or Inspector roles, the only next step available was discard, which was is filtered from the schema options. This meant the "What do you want to do?" section never rendered.
This now shows the "What do you want to do?" section even if the only action available is discard.
With multiple options:
With only discard option:

Display the what next section if there is a discard option

---

pages/task/list/views/table.jsx
pages/task/list/views/tasklist.jsx

So we can render tasklists as tables without the filters and progress tabs, but without having to redefine all the formatters.

Put tasklist table into separate component

---

pages/common/assets/sass/style.scss

As seen on the external home page and global profile pages. These random borders and backgrounds look super nasty and should be removed.
Before:
After:

Remove grey background from expanding panels inside panel lists

---

pages/common/assets/sass/style.scss

HOLCs have a load of margin but SPoCs and inspectors are compact. Make them all compact.

Make spacing on establishment dashboard roles consistent

---

pages/common/routers/datatable.js

Stop capping the limit at 100 rows because there's a legit need for arbitrarily large tables.
We could add an arbitrarily larger limit limit but Y THO?

Remove limit limit on datatables

---

pages/project-version/update/submit/content/index.js
pages/project-version/update/submit/index.js
pages/project-version/update/submit/schema/index.js
pages/task/index.js
pages/task/read/content/base.js
pages/task/read/views/models/index.jsx

I attempted to rename "comments" to "reason" for clarity, but it affects more than just projects. We should revisit with a view to renaming it for all licence types, but for now lets get it working with the existing field name.

Fix the "reason for amendment" question in tasks

---

lib/utils/index.js

If the saved result for a model is null, then `hasChanged` returns true for empty strings. Make it so that only a change to a truthy value counts as a change if the underlying field has a null value.
Specifically it's currently possible to submit a place amendment with no changes if the restrictions are null, because `isEqual('', null) === true`

Fix comparison of null fields

---

pages/pil/read/content/index.js
pages/pil/read/views/index.jsx

If a user has permission to edit a pil, and views it scoped to a secondary establishment, enable update/revoke under primary establishent

Feature - allow pil updates from secondary establishment

---

pages/project-version/read/index.js
pages/project-version/read/js/index.js

isGranted is false for legacy licences, and messes with layout. Added extra setting for legacy

Added legacyGranted setting

---

pages/role/apply/index.js
pages/role/remove/index.js
pages/role/remove/schema/index.js

Currently the add role screen omits roles if the user already holds them, irrespective of what establishment they hold them at.
Filter the list of excluded roles to only those that are held at the current establishment.

Allow adding roles from other establishments

---

pages/profile/permission/index.js

If a user has roles and projects at any establishments then they can't be removed from other establishments.
Make sure that roles and projects have establishment ids that match the current estasblishment when removing permissions.

Check roles and projects have correct establishment when removing permissions

---

pages/project-version/update/index.js
pages/project-version/update/js/index.js

If a user ends up on `/edit` for a version that is not a draft then redirect them away to the readonly URL.
Also add `urls` to initial state for update view so that links work correctly where used.

Redirect edit URL to readonly view for non-draft PPL versions

---

pages/project-version/update/index.js

If we redirect non-draft versions before the success page router then we never render success pages on submission.
Instead move the redirect down so success pages can render correctly.

Move redirect to below success page router

---

pages/project/read/index.js

* we were previously updating the top level id in the task when a project was forked - this should have been the project id, which resulted in broken task screens in some situations.

Bugfix - use forked id from data

---

pages/project/read/views/index.jsx

When an ASRU LO starts adding additional data to a stub, it creates a new draft version.
This version should not be visible to non-LOs (internal or external) until it has been converted into a standard licence.

External users should not see in progress stub changes

---

pages/project/read/views/index.jsx

If a stub is expired, we should still be able to add more details or discard it.

Don't hide project landing page actions for stubs

---

pages/project/read/views/index.jsx

By using the first version always then we end up showing a draft banner whenever a draft exists.
Instead use the granted version if one exists.

Use granted version for landing page status banner if it exists

---

pages/task/read/routers/read.js

It's not only update tasks that don't have a version id, also revocations. Reverse the condition to use a version endpoint where a version id is defined, but use the project endpoint in all other cases.

Handle all cases where a project task doesn't have a version

---

pages/pil/procedures/index.js
pages/pil/species/index.js

Previously if the session had expired then this threw an error. Instead allow the session data to be re-created with the submission and the PIL application continued.

Handle missing PIL session when saving species and procedure data

---

pages/task/read/views/models/project.jsx

If a change of PPL holder task auto resolves then it must be a draft, but we still send a notification with a link to the task, which currently fails because there's no granted version.

Prevent error when viewing autoresolved PPL holder change

---

pages/common/routers/success.js
pages/establishment/apply/index.js
pages/pil/revoke/index.js
pages/project-version/convert/index.js
pages/project-version/update/success/index.js
pages/project/revoke/index.js
pages/project/update-licence-holder/index.js

The way that dynamic statuses or models were configured they needed to create a complete router for every request. Move the dynamic bits into getter functions which are passed into the router constructor as params, and so can mount a single router instance.

Remove per-request router creation

---

pages/common/routers/success.js

* settings are being overwritten which results in future calls remembering the previous value

Bugfix - dont overwrite settings

---

pages/project/update-licence-holder/content/index.js
pages/project/update-licence-holder/routers/confirm.js
pages/project/update-licence-holder/routers/update.js
pages/project/update-licence-holder/views/confirm.jsx
pages/project/update-licence-holder/views/index.jsx

This action autoresolves so display a toaster instead of a success page.

Hide the experience questions when udpdating lh on a stub

---

pages/task/read/content/profile.js

* We extend base profile content, which has a title, which nukes the default

Bugfix - missing profile task title

---

pages/common/assets/sass/style.scss
pages/establishment/licence-fees/views/index.jsx

Binding this style onto the tab content doesn't make sense when we have download links not in the context of tabs.
Add a generic "table-wrapper" class for positioning CSV download links near tables.

Add generic class for positioning csv downloads near tables

---

pages/pil/review/index.js

To prevent errors or data leaking from PIL amendment add a suffix to the model id when performing a PIL review.

Use unique model.id for PIL review form

---

pages/task/read/content/profile.js

Task pages lookup content for comments depending on task type, so the content needs to be scoepd under "amendment" (which is the only type of profile task)

Restructure profile amendments content

---

pages/common/helpers/pdf.js
pages/establishment/pdf/index.jsx
pages/pil/pdf/index.jsx
pages/project-version/pdf/index.jsx

Extract a common PDF renderer component and reduce the amount of repeated rendering code used across page routers.
Adds a `noRender` option to all PDFs. This will prevent the PDF renderer assuming we're passing a mustache template and trying to check over a several megabyte string for a mustache token regex.

Extract PDF renderer helper

---

pages/common/content/success-messages.js

* Added success message for autoresolving pil application (LO revokes and resubmits)
* Added success message for non-licensing internal user submitted a revoked pil to licensing

Bugfix - missing PIL success messages

---

pages/project/read/index.js

The parameter name was changed from `version` to `versionId` so needs this to redirect correctly.

Correct version parameter in workflow fork response

---

pages/pil/read/content/index.js
pages/pil/read/index.js
pages/pil/read/views/index.jsx
pages/profile/index.js

Currently if a user has left the establishment that they once held a PIL at (and it is revoked) then they can't easily reapply for a new licence.
Add an extra check to revoked licences that the user is still at the PIL holding establishment, and present different paths forward depending on the case - either reactivating an old PIL or creating a new one.

Allow users to apply for a new PIL if they leave an establishment

---

pages/project-version/update/router.js

Instead of launching a follow-up GET request, use the payload of the PUT response to update the local version state.

Use response from project version PUT

---

pages/common/assets/sass/pdf/index.scss

* Set mav height to 100vh to prevent images splitting over pages
* Avoid page breaks in images

Bugfix - pdf images fixes

---

pages/project-version/index.js

When a comment was added we would assign the id from the most recent activity log entry, not the most recent comment. This would prevent comments being deleted until page reloaded

Bugfix - deleting comments

---

pages/task/read/routers/read.js

Establishment tasks were trying to load `/establishment/undefined/establishment/id`. This fixes that so establishment model tasks load the right API endpoint.
Also simplifies the code a little.

Fix API urls called when loading tasks

---

pages/task/read/routers/read.js

The `estId` parameter was used in places other than where it was defined.

Fix variable initialisation in task API requests

---

pages/common/views/success.jsx
pages/pil/review/views/success.jsx

If a user has permissions to view the PIL list then replace the "Home" link that lives on the success page by default with a link to the PIL list for the establishment.
Also moves the success page component fully into this repo. 100% of instances of the success page in the app load `./pages/common/views/success.jsx` from this repo, which was delegating directly to `@asl/components`, but this extra abstraction doesn't seem to add any value except to make development more involved.

Add link to PIL list to review success page

---

pages/common/content/index.js
pages/common/routers/related-tasks.js

Some content was being added to the common content file, but not all things.
Take the task list content out of the common file so it is not loaded when related tasks are not shown, and merge the entire task list content file when related tasks are loaded.

Merge all task list content in related task router

---

pages/project-version/pdf/views/nts/components/retrospective-assessment.jsx
pages/project-version/pdf/views/nts/v0.jsx
pages/project-version/pdf/views/nts/v1.jsx

* RA condition is dependent on `retrospectiveAssessment` property, and not `retrospectiveAssessmentRequired` (which flags if it is non-optional)
* RA property is on version and not project
* RA section was missing from legacy NTS
* Fix typo

Fix bugs with RA condition in NTS downloads

---

pages/role/remove/index.js

Right now no role removal tasks have model data set, so this fails on all multiple role removals.
There will be a parallel fix to workflow to add the model data and make this work at all.

Handle role remove tasks without `modelData`

---

pages/project-version/middleware/index.js

The cache never expires, so if a user looks at a lot of things without logging out then their session store becomes massive, and eventually DoS-es the service.
Add a cache parameter to the `req.api` call to facilitate better caching at an API client level.

Remove overly crude caching implementation on project versions

---

pages/project-version/update/router.js

Allows the client to detect remote changes when patching projects.

Include checksum in project patch response

---

pages/project-version/pdf/index.jsx

The legacy PPL already is the full application, and so the logic inside projects causes lots of content to end up repeated if it is a legacy project _and_ the `isFullApplication` flag is set.
Set `isFullApplication` to false always for legacy PPL PDFs so that the content is not repeated.

Disable "full application" for legacy PPLs

---

pages/common/views/pdf/footer.jsx
pages/common/views/pdf/header.jsx
pages/project-version/pdf/index.jsx

Make the official sensitive content in the header and footer of PDF downloads optional - defaulting to true, and remove it specifically from NTS document.

Remove official sensitive warning from NTS pdf download

---

constants/index.js
pages/establishment/licence-fees/personal/views/row.jsx
pages/establishment/licence-fees/views/index.jsx
pages/global-profile/views/index.jsx
pages/pil/dashboard/views/index.jsx
pages/pil/read/views/index.jsx
pages/profile/convert-legacy-project/views/confirm.jsx
pages/profile/invitations/views/index.jsx
pages/profile/read/views/index.jsx
pages/profile/read/views/profile.jsx
pages/project-version/components/project-status-banner.jsx
pages/project/read/views/index.jsx
pages/task/read/views/components/activity-log.jsx
pages/task/read/views/components/deadline.jsx
pages/task/read/views/models/project.jsx

Adds a new `long` date format (which is the same as the old `medium`) and sets `medium` to use truncated months.
Use `medium` in table contexts to save space and `long` in non-table contexts.

Reformat dates in table contexts

---

lib/utils/index.js

We used to assume all arrays are to be compared with isEqual, however now we have arrays of objects we need to map using the accessor

Bugfix - task diff

---

pages/common/middleware/index.js
pages/place/index.js
pages/profile/index.js
pages/project/index.js
pages/task/index.js

Check that UUIDs are the correct format before making a call to the API, and throw 404 if not.
Certain unchecked inputs can cause the http client to throw if used in API request URLs, so validate the user input from the URL before making a call using it.

Validate UUID url parameters

---

pages/task/read/content/pil.js

The PIL content inherits a label for `status` which then appears erroneously in the next steps section of a PIL task.
Ensure this is unset correctly for PIL tasks and not inherited.

Unset status label on PIL tasks

---

pages/project-version/update/router.js

The required version is a range, and not an explicit version so it needs to be converted to an explicit version before it can be used as an argument in version comparison.

Fix semver comparator

---

pages/user/update-email/routers/confirm.js

This currently throws an error if the user attempts to access the confirm page when the values are not present on the session. Instead redirect to the previous page and allow a restart.

Redirect change email confirm page on session expiry

---

pages/establishment/licence-fees/index.js
pages/establishment/licence-fees/views/index.jsx

Instead of importing the constants directly, use the API as the canonical reference for the years available.
Context: a change to filter the list of available years is coming, and this means it can be done in one place only.

Use list of available years from API response

---

pages/task/read/views/models/pil.jsx

Where the PIL task is not an application then do not show the "over 18" component on the task screen.

Remove "over 18" component from some PIL tasks

---

pages/task/read/routers/read.js

If a task is discarded then the version is deleted. So without this the success page throws a 404.

Pass `withDeleted` flag when fetching version

---

pages/task/read/routers/read.js

Top-level project call will 404 for receiving establishment so need to get version first.

Fetch project version directly for PPL transfer tasks

---

pages/task/read/routers/read.js

If the task is closed and therefore the "before" state is loading from `modelData` then no permissions check is made on the user's ability to see the task data, and therefore tasks can potentially be exposed to unauthorised users.

Move override of "before" state to after API calls

---

pages/task/read/routers/read.js

Reverts UKHomeOffice/asl-pages#906
I've managed to break something somewhere in here, so I'm going to revert it in favour of more robust permissions checks at an API level.

Revert "Move override of "before" state to after API calls"

---

pages/project/update-licence-holder/routers/confirm.js
pages/project/update-licence-holder/routers/update.js

The change PPL holder journey previously fetched the granted version, which meant it failed on drafts.
Get the most recent available version on drafts and the granted version for non-drafts.

Allow change PPL holder on draft PPLs

---

lib/utils/index.js
pages/common/assets/sass/style.scss
pages/task/content/status.js
pages/task/read/content/project.js
pages/task/read/views/components/activity-log.jsx
pages/task/read/views/components/deadline.jsx
pages/task/read/views/components/ppl-declarations.jsx
pages/task/read/views/components/task-status.jsx
pages/task/read/views/models/project.jsx

* Moves the deadline to the top of the page in the status section
* Deadline before/after will display in the activity log for deadline extension activity
* Deadline passed warning on both of the above when applicable
* AWERB / ready / authority playback was simplified

Improvements to statutory deadlines in task view

---

pages/project-version/update/submit/index.js

The version data is not used to render the form, and results in multiple copies of the data property being held in memory inside the form router.
For large PPL data blobs this results in OOM errors. By removing all except the title - which is used to render the page - from the data blob then the memory usage of the page render is reduced by ~99%.

Don't copy complete project data to req.model

---

pages/project-version/update/success/index.js

`req.model` isn't used downstream anywhere, so it's just using memory for no reason.

Remove redundant copy of `req.version`

---

pages/establishment/dashboard/views/index.jsx
pages/profile/list/views/index.jsx

List of users and roles in the establishment sidebar and people lists are sorted in an arbitrary way which means they keep throwing false-positives in regression tests.
Apply a sort to these cases to ensure that they are always ordered consistently.

Ensure lists are ordered in a stable way

---

pages/task/read/routers/read.js

We think this is where a nacwo is assigned to a place with a task related to it, but has since had the nacwo role removed.

Handle case where NACWO cannot be found

---

pages/establishment/dashboard/views/index.jsx

The previous sort property was undefined for all records because the structure for HOLCs is different to the inspectors and SPOCs. It worked most of the time in testing by coincidence.

Fix sort property on HOLCs

---

package-lock.json
package.json
pages/project-version/middleware/index.js

This function gets a list of keys of all the questions on a PPL data blob. It needs to stop when it finds objects of the shape of a rich-text-editor blob because that's no longer a question grouping, but an answer.

Don't traverse into text editor data when finding PPL object keys

---

pages/common/middleware/load-permissions.js
pages/profile/read/index.js

By default `allowedActions` only includes tasks that a user can _always_ perform, and does not include permissions which vary depending on the exact entity being viewed.
The `loadPermissions` middleware allows a selection of tasks to be dynamically loaded into `allowedActions` based on the current request params.
In this particular case it adds the training permissions to profiles, which for non-admin users is dependent on whether they are viewing their own profile or not.

Add middleware to dynamically load selected permissions into `allowedActions`

---

pages/establishment/licence-fees/content/index.js
pages/establishment/licence-fees/index.js
pages/establishment/licence-fees/views/index.jsx

The top-level `title` property was already being used, so this needs to go back to how it was before to keep the correct page h1 heading.

Restore correct headings to billing pages

---

pages/task/read/content/place.js

The task base content has `title` as an object with several properties defined. Inheriting the string `title` property from place content overwrote this and prevented the correct title from being available.
By setting the title property for place-specific content with an empty object the string is no longer merged onto the object and the default title properties are preserved.

Prevent inherited place content overwriting title

---

pages/establishment/licence-fees/index.js

This router doesn't mount a page router, and so doesn't load local content onto res.locals.
Go fetch the content manually instead.

Load content for page title

---

pages/place/index.js

It's currently showing `undefined` because it doesn't use a page router. Load content directly.

Fix "approved areas" page title

---

pages/pil/dashboard/views/index.jsx

The API response has different structure for procedures depending on whether it was loaded from `/pil` or `/pil/:id`. Modify this code to leave the procedures intact if they already have a `key` property set. This then supports procedures in either structure.

Normalise PIL procedures

---

pages/task/read/views/models/pil.jsx

Depending on the API endpoint used for the data the procedure categories can be in different forms. Normalise the forms.

Normalise PIL categories in task view

---

pages/pil/index.js

Inside the `pilId` param call `req.pil` is the specifically scoped "normal" PIL, as opposed to the aggregated PIL model which is set to `req.model` further down.
This needs to set `req.model` so that it is pointing at the "normal" PIL in contexts where that is being acted on.

Restore setting of req.model = req.pil

---

pages/profile/read/index.js

If viewing a profile as a basic user then you won't have permission to view the PIL. Don't 404 the entire profile if the PIL request returns a 404.

Don't throw error if PIL API request fails with 404

---

pages/profile/read/views/profile.jsx

The button to apply for a PIL was shwing when the user already had an active PIL at another establishment.
Hide the button if a user has an active PIL at any establishment.

Fix logic for display of PIL application CTA on profiles

---

pages/pil/read/index.js
pages/pil/routes.js

The extra breadcrumb for viewing a PIL was being applied to all sub-pages of the PIL journey. Instead only add the "View Personal Licence" breadcrumb when actually on that page.

Fix breadcrumbs on PIL application/amendment

---

pages/pil/procedures/views/diff.jsx

The diff had been removed from the procedures list for changes to the notes around category D/F PILs because the props passed into the `Item` component no longer included the notes.
* Pass the complete before and after state of the PIL into the `Item` component so it can correctly highlight changes to the notes.
* Move the `className` to only wrap the content and not the header for notes changes.
* Remove a redundant `Fragment`

Apply diff highlighting to Category D/F notes in PIL amendments

---

pages/success/index.js

* If req.establishment is set, use that for success page rather than task establishment, this shows the transfer to est for pil xfers

Bugfix - use scoped est if set

---

pages/pil/read/index.js

The URL to view a PIL has moved from `/pil/:id` to `/pil`. Redirect any users trying to access old urls to the new url.

Redirect from /pil/:id to /pil

---

pages/project/read/content/index.js
pages/project/read/views/index.jsx

Users are prevented from changing PPL holder while there are open tasks. Show a reason why instead of just hiding the link.

Explain why the change ppl holder action is missing

---

pages/common/assets/sass/pdf/index.scss

* Because of the way table headers are rendered in pdfs, conditions spanning multiple pages render with a streteched border overlapping the table header - avoid page break in a condition

Bugfix - conditions border overlap

---

pages/pil/unscoped/list/schema/index.js

Licence numbers are stored on a profile now, so the sort property on that column needs to be defined as that or it fails out.

Fix sorting PILs by licence number

---

pages/pil/dashboard/views/index.jsx

These were lost with this commit - https://github.com/UKHomeOffice/asl-pages/commit/4830e73a239262c62edfb10eb292a3a026bc1285#diff-94db34bb992d2c29c037feb2a25fc9864a6c43875ad1b1045450989642ad73cfL30-L31

Restore two-thirds wrapper to PIL declarations

---

pages/pil/create/index.js

The previous way of doing a fetch immediately after creation fails when a profile has an active category E PIL because the API response changes.
Instead use the id of the newly creted record which is returned on the workflow response from the create task.

Fix redirect to newly created PIL

---

pages/user/menu/views/index.jsx

Make the manage training link appear in the same way as the other sections.
Also hide it for ASRU users for whom it is not relevant.

Standardise account page

---

pages/establishment/licence-fees/personal/schema/index.js

Sort poperty needs to be `pilLicenceNumber` because that is the name fo the property on a profile.

Fix sorting billable PILs

---

pages/common/routers/form.js

This prevents any unintended side-effects of setting properties on the schema during the request pipeline being persisted in the global state.

Clone schema in form configuration

---

pages/project-version/update/index.js

If a user has submitted an application for endorsement which has then been returned then it will still have a status of draft, this prevents the user from editing that version and bumps them to the editable version.

Don't allow editing a version that is not the most recent

---

pages/project-version/update/index.js

If there is no draft version then this throws an error. This occurs when a user has bookmarked the edit page of an application, which is then granted.

Check draft exists when comparing ids

---

pages/project-version/update/index.js

If a draft has been submitted to the PEL holder delegate for approval, but has not yet been submitted to ASRU then it has a status of `draft` however it should no longer be editable at this point.
Check if there is an open task for the project and if the task is not editable then redirect to the read-only route of the project version.

Don't allow edits to project versions if there is an open task

---

pages/project-version/middleware/index.js

Where an additional establishment on a PPL has changed get the name correctly independently of whether it was added as a data link by id, or using a free text input.
This means that the old values display correctly in comparison windows and changed indicators show as appropriate.

Show changes correctly for establishment fields

---

pages/task/read/views/models/project.jsx

This shows the `and` even when there is only one establishment.

Remove random `and` from notice

---

pages/common/routers/datatable.js

This is the maximum number of rows that elastic will allow by default, and it throws an error if more are requested.
Since no table that uses the CSV export has more than 10,000 rows this should be fine.

Set datatable CSV download limit to 10,000

---

pages/profile/permission/index.js

If a person holds a PPL with an additional availability at an establishment then they should not be able to have permissions removed.

Prevent removal of permissions from AA PPL holders

---

pages/pil/dashboard/content/index.js

This prevents any legacy PIL-Es from throwing errors when amended. Noting that they can only be amended to a state without a PIL-E as a normal procedure.

Add PIL E field labels to PIL amendment dashboard

---

pages/project/read/views/components/current-activity.jsx

When viewing a project with open tasks as a read-only user, do not render the open tasks table if the flag to show related tasks is not set (a.k.a. the user does not have appropriate permissions).

Don't show related tasks to users without permissions

---

pages/project-version/middleware/index.js
pages/project-version/read/js/index.js
pages/project-version/update/js/index.js

If looking at a draft PPL with more than 2 iterations then also return a comparison between the current version and the first submission.

Return changes from the first submission in PPL applications

---

pages/project-version/middleware/index.js

There is downstream code in projects which expects this to be available, and is currently throwing errors.

Include initial submission in `previousProtocols`

---

pages/common/assets/sass/pdf/index.scss

I can't work out what this is intended to achieve, but it results in unexpected behaviour when rendering PDF documents, that is hard to decipher when working with the JSX.
Remove it, and if it has any ill effects then resolve those in the JSX directly.

Remove unwanted CSS selector

---

pages/establishment/update/content/index.js

The field was renamed to `comment` but this message wasn't changed

Fix broken error message

---

pages/task/read/routers/deadline-passed.js
pages/task/read/routers/extend.js

The built-in method for setting form schemas does a `cloneDeep` so removes any possibility of accidental schema mutation across requests. There is no need to repeat the process.
Note: this is in response to some odd integration tests failures, which are sporadic but look a lot like the result of schema mutation in task processing.

Use automatic schema config for forms

---

pages/project/update-licence-holder/routers/confirm.js
pages/project/update-licence-holder/routers/update.js
pages/project/update-licence-holder/schema/experience-fields.js
pages/task/read/views/models/project.jsx

Legacy PPLs use a different question for PPL holder experience, so the existing set of questions from new-style PPLs does not correctly update the PPL data.
Pass the PPL schema version to the schema generator function so it can return the correct set of experience questions depending on whether the PPL is legacy or new style.

Use correct fields for experience when changing PPL holder

---

pages/project/read/views/components/user-cannot-edit.jsx

We were displaying both the "Open Task" panel and the "cannot edit" panel once the amendment was submitted - we only want to display the former in that case, and vice versa.

Hide the unsubmitted amendment warnings when there is an open task

---

package-lock.json
package.json
pages/place/schema/index.js

You could already remove an assigned NACWO / NVS by choosing the empty select option, but it wasn't obvious. Allow the user to remove the entire select box even if it's the only one.
~waiting on https://github.com/UKHomeOffice/asl-components/pull/185~

Allow all role selectors to be removed

---

pages/project-version/middleware/index.js

Some protocols are null sometimes because reasons. Try not to blow up in those circumstances.

Handle null protocols when normalising protocol conditions

---

pages/task/list/router.js

This means that the default sorting parameters that are applied dynamically are exposed to the client, and so can be reflected in the UI.
This in turn means that clicking the sorting header on the `updatedAt` column will _always_ reverse the sort, and you won't need to click it twice to get the latest tasks.

Move sorting logic on task list to pages router

---

pages/project/content/index.js
pages/project/formatters/index.jsx

Currently projects which are revoked but also have passed their expiry date are showing as expired rather than revoked when listed in tables.
Since all active projects have their status set to `expired` on expiry there is no reason not to trust the project status and use it directly.

Fix status on revoked projects that are passed their expiry date

---

lib/middleware/csrf.js

There appears to be a race condition where the POST to a form sometimes is received before the previous token has saved, so checks the csrf token against a stale session value.
Force the token to be saved to the session store on a form GET before sending the response to ensure that the subsequent POST will always have the fresh value.

Force CSRF tokens to be saved to session store

---

pages/project/read/views/components/current-version.jsx

The pdf link on the overview page was linking to the "licence" view pdf rather than the application view.

Ungranted pdfs should always be the application

---

pages/task/read/routers/confirm.js

If the session is not available then prevent throwing an error.

Use a `get` to handle missing session

---

pages/pil/procedures/views/diff.jsx

160 PILs in production have been updated from categroy F to category E. These don't have any training course metadata attched to them, but do have a note.
For those cases when rendering the PIL on the PIL page we want to show the notes instead of blank training course data.

Show notes on old cat F pils which are converted to cat E

---

pages/project-version/middleware/index.js

If there is an open task in progress on an AA project don't try to load the comments if viewing from an additional establishment. The request to the task will fail causing an error because it is a task from another establishment.

Don't try to load comment on AA project applications

---

package-lock.json
package.json
pages/project-version/middleware/diff/compare.js
pages/project-version/middleware/diff/worker.js

Invisible unicode characters like `\uFEFF` cause word boundaries to be added where none actually exist, and string lengths to be miscalculated.
Remove any invisible unicode control characters from text before performing comparison to ensure that the changes render correctly.
~WIP pending projects bump~

Remove invisible unicode from editor values in comparison

---

pages/project-version/middleware/index.js
pages/project-version/read/index.js
pages/task/schema/confirm.js

ASRU users should not see comparison of draft PPL/RA versions which have not been endorsed for submission to ASRU.
When finding the available versions for comparison then use a filtered list when request is being made as an ASRU user. Establishment users will see all available versions.

Filter available versions for comparison based on user type

---

pages/project-version/middleware/index.js

Workflow can sometimes respond with an error object and not a task, which means `task.data.action` throws an error because there is no data property.
Use `get` to access the action to avoid an unnecessary error when that happens.

Use `lodash.get` to read action property

---

pages/project/read/views/components/start-amendment.jsx
pages/project/update-licence-holder/routers/confirm.js
pages/project/update-licence-holder/views/index.jsx

Don't allow PPL holder changes to be made if there is an open, but unsubmitted PPL amendment in progress.

Prevent changing licence holder when there is an amendment

---

pages/rops/update/config.js

If a value is `null` then `lodash.get` retains the null rather than applying the fallback, so this needs a separate default value to avoid `ropSpecies.precoded` throwing an error when `ropSpecies` is null (which it seems to be if you answer "No" to the "any more species" question).

Add default values for ROP species

---

pages/common/routers/datatable.js

This allows UTF8 characters to render correctly in Excel.

Add BOM to CSV downloads

---

pages/rops/procedures/schema/index.js

If no extra species are added then the rop species list is `null`. Set a default value so `Object.values` doesn't throw.

Default to `{}` if species is null

---

pages/task/read/views/models/training-pil.jsx

If a user has an old revoked PIL, then these procedures are still included on the task page when applying for a PIL, which has led to some confusion with inspectors/LOs who are uncertain if this will re-activate the old procedures.

Don't include revoked PIL procedures on PIL-E tasks

---

pages/project/read/views/components/details.jsx

The permissions check was too high up so was hiding the issue date of PPLs to everyone except ASRU licensing officers.

Allow visibility of PPL issue date to users who cannot change it

---

pages/rops/update/views/components/confirm.jsx

The questions in ROPs about NHPs are checkbox groups that support multiple selections, but weren't configured to handle arrays.
Modify the `getRadioOption` to deal with array values automatically, and clean up the code which handled arrays similarly on a per question level so they use the same approach.

Handle arrays in `getRadioOption` function

---

pages/common/routers/multi-step.js
pages/rops/update/config.js
pages/rops/update/index.js
pages/rops/update/schema/index.js

* If no other species selected, then species are removed from rop
* This functionality is disabled if any of the rop species have had procs added

Bugfix - remove species from rop if no other species selected

---

pages/rops/procedures/schema/index.js

When the re-use question was removed, the reveal for places of birth that was shown when answering "no" to re-use was also incorrectly removed. Restore the place of birth question as a direct child of the species when the setup does not include re-use.
Additionally display NHP questions as well as re-use when NHPs and re-use are selected.

Always ask place of birth question unless re-use

---

pages/role/remove/index.js

If a user holds the same role at multiple establishments then the `find` doesn't reliably return the right one.
This results in broken tasks that can't be loaded because the establishment id and role id don't match so throw 404s.

Check establishment id when removing roles

---

pages/place/routers/update.js

If the user does not click done on restrictions when adding/editing a place then there is a hidden field and textarea with the same name/value posted, and so the value appears twice in the POST body as an array.
Normalise this back to a single field if it occurs.

Handle user not clicking "Done" when adding place restrictions

---

pages/rops/procedures/create/views/index.jsx

This allows users to return to the procedures list on their ROP without adding or changing a procedure.

Add cancel button to procedure add/edit screen

---

pages/rops/procedures/list/views/index.jsx

When accessing the procedures page for the first time there are two large green buttons with equal prominence, which makes it difficult for a user to know easily how to proceed.
Since it would be incorrect at this point to submit to return with no procedures then don't show the submission button until at least one procedure has been added.

Hide submission CTA if there are no procedures

---

pages/project/read/views/components/rops.jsx

If the year for the ROP is inferred from the calculated deadline then it will generally be off by one as the deadline for most 2021 ROPs is in January 2022.
Hard-code 2021 until handling multiple years becomes relevant in late 2021/early 2022 and a proper design spec is created.

Fix ROPs year in reporting tab of project overview

---

pages/rops/procedures/list/views/index.jsx

The unsubmit should still be available for ROPs that might have been submitted with no procedures.

Allow unsubmit of a ROP with no procedures

---

package-lock.json
pages/rops/procedures/schema/index.js

Where a user has selected an "other" species group in the setup questions and provided a text input, both the "Other" value and the text input are presented as options on the procedures input screen.
Filter the values to get rid of any `other-*` values.

Remove "Other" species added in ROP setup

---

pages/common/assets/sass/style.scss
pages/common/components/overflow-wrapper.jsx
pages/rops/procedures/list/views/index.jsx

This adds a gradient on each side of the container when it is hidden by horizontal scrolling.

Add ScrollWrapper component to show indicators on wide elements when scrollable

---

pages/establishment/licence-fees/personal/schema/index.js
pages/pil/unscoped/list/schema/index.js

Establishments requested that the two name fields be separate to make them easier to work with.

Split name into two columns in establishment PIL lists

---

pages/task/content/status.js
pages/task/read/views/components/activity-log.jsx

Some tasks are automatically discarded by a worker. Don't render `undefined undefined` as the name in the activity log in those cases.

Remove names from activity log when action was automatic

---

lib/utils/index.js

If before and after values are both falsy then don't flag a change

Don't show null changes in diffs

---

pages/common/middleware/index.js
pages/project/read/views/components/change-licence-holder.jsx
pages/project/update-licence-holder/routers/confirm.js
pages/task/read/views/models/project.jsx

* Show change licence holder component if editable task
* Dont redirect to task if changing licence holder and inactive
* replace success screen with toaster
* Show licence holder from project, not submitted version on task

Feature - change licence holder - ppl draft

---

pages/rops/procedures/list/formatters/index.jsx
pages/rops/procedures/list/index.js
pages/rops/procedures/list/schema/index.js
pages/rops/procedures/list/views/index.jsx
pages/rops/update/views/components/confirm.jsx

Display the free text entered by the user when selecting any of the "other" regulatory sub-purposes.
Note that the ROP data is now passed to the procedures list schema so we can get the "other" values from the ROP. The alternative was to return the same ROP with every row of procedures from the API, which seemed like a lot of unnecessary data transfer.
I recommend hiding whitespace changes for the review.

include "other" free-text when rendering regulatory subpurposes

---

lib/utils/index.js
pages/task/read/content/deadline-passed.js
pages/task/read/routers/deadline-passed.js
pages/task/read/views/deadline-passed.jsx

* Pass the task in the page params so that the deadline metadata is accessible
* Update the content
* Add a default date format so only one wild require path is needed to do a date formatting

Fix deadline passed content

---

pages/success/index.js

Since the title is liable to change from the original model data through the task lifecycle, use the project title as a preference rather than the modelData value to ensure it is up to date if the title is changed during an iteration.

Use project title in favour of modelData on project submission pages

---

pages/rops/update/schema/index.js

Without a default value then it is not possible to return to a legacy project ROP if it was abandoned at the species selector step because it throws an error trying to call `Object.values(undefined)`.

Add default value to species validator

---

pages/project-version/middleware/index.js

* legacy licences show application view, therefore diff windows if version has a diff from granted - granted should be granted before current version (not current licence) as this ends up with wild diffs

Bugfix - point to correct version for diff

---

pages/rops/update/schema/index.js

If the species free-text field is never interacted with, then the value is undefined rather than an empty array, which causes an error if you attempt to read the length.

Default array before reading length

---

pages/project-version/middleware/index.js

* Handle case where the previous granted version does not exist, and error was thrown reading id property. Instead resolve early.
* Handle lookup of granted RA correctly

Fix bug with granted version lookup

---

pages/project-version/middleware/index.js

If an ASRU users is looking at a draft PPL version which is currently with the applicant then that version is not included in the set of available versions for comparison, which causes errors to be thrown because the right versions cannot be found.
Always include the version currently on screen in the set of available versions so that the numebr of iterations makes sense when looking at the most recent draft version of a returned PPL application.

Always include currently viewed version in list of available versions

---

pages/profile/permission/views/index.jsx

Adding a disabled prop to the link doesn't change its behaviour - if the user clicks on the disabled link they are still taken to the remove page.
Instead of the link, render a disabled button when the functionality is required to be switched off.

Render disabled button if user cannot be removed from an establishment

---

pages/common/assets/sass/style.scss

The whitespace on definition lists looks a bit wonky if there are ULs in it as the last item, as both the UL and the DD have margin-bottom that adds up.

Remove double margin from ULs in DDs

---

pages/task/read/views/models/establishment.jsx

currentLabel / proposedLabel were being passed as `false` which was overriding the defaults

Diff headers were missing for incomplete PEL tasks

---

pages/rops/components/header.jsx
pages/rops/components/procedures-download-link.jsx
pages/rops/helpers.js
pages/rops/index.js
pages/rops/nil-return/views/index.jsx
pages/rops/procedures/list/index.js
pages/rops/procedures/list/views/index.jsx
pages/rops/procedures/schema/index.js
pages/rops/submit/views/confirm.jsx
pages/rops/submit/views/index.jsx
pages/rops/update/index.js
pages/rops/update/views/components/confirm.jsx
pages/rops/update/views/components/endandered.jsx
pages/rops/update/views/components/reuse.jsx
pages/rops/update/views/components/schedule2.jsx
pages/rops/update/views/components/species.jsx
pages/rops/update/views/index.jsx

The complete version data is being included in three different places in `INITIAL_STATE` which causes very slow load times for large projects.
None of these need to be sent if we move the basic calculations being done on the client to the server and send calculated props as required.
Also remove duplication of `state.model` and `state.static.rop` to further reduce redundant data in the payload.

Optimise data payloads for ROPs

---

pages/rops/components/header.jsx
pages/rops/nil-return/index.js
pages/rops/submit/index.js

* Prevent router falling through to project router and overwriting `res.locals.model`.
* Read establishment data from project to get around inconsistency with `static.establishment` existing in some places but not others.

Fix props for ROP submission

---

pages/rops/helpers.js

This was looking for a `ga` flag on the version data, which does not seem to exist. Check each protocol for the `gaas` field.

Fix check for GAAs on new style PPLs

---

pages/profile/read/views/profile.jsx
pages/profile/routes.js
pages/project/read/index.js
pages/project/read/views/components/amend-stub.jsx
pages/project/read/views/components/discard-stub.jsx
pages/project/read/views/components/start-amendment.jsx

These are no longer bound to licensing officers. Move the permissions logic to the permissions service so that if they need to be changed in future then they can be changed once.

Use permissions service to determine stub conversion permissions

---

pages/project-version/nts/schema/legacy.js
pages/project-version/nts/schema/standard.js
pages/project-version/nts/views/components/retrospective-placeholder.jsx

* If ra is added to a submitted draft and the nts printed before approval, raDate is null
* in this case render standard 6 month content rather than 1970
* Replaced mustache-like-code with mustache

Bugfix - dont try and render null date

---

pages/task/read/routers/confirm.js
pages/task/read/views/components/ppl-declarations.jsx

Bonus fix: re-populate the awerb date field on re-endorsement if present.

Only show the relevant declaration questions for each item in the activity log

---

pages/common/routers/multi-step.js
pages/rops/update/config.js

If a nil-return is triggered then journey abandonned, the logic to determine which step the user should be redirected to doesn't take target into account.
* Updated logic for nil return to redirect if either condition is true
* Updated multi-step router logic to apply target function of previous step if present

Bugfix - rop nil return logic

---

pages/pil/read/index.js

If the PIL does not exist then return a 404 page rather than throwing an error by trying to read the status property of null.

Handle null PIL with a 404

---

pages/project/read/index.js

The ROP is only applicable to the establishment which holds the licence, so don't show the reporting tab for transferred out projects.

Don't show ROPs tab for projects left behind following a transfer

---

pages/common/routers/datatable.js

Excel and other spreadsheet apps commonly used to open CSVs, try to "helpfully" format strings that vaguely look like numbers as actual numbers which can lead to weird outputs.

force strings to display as strings in CSVs

---

pages/pil/read/content/index.js
pages/pil/read/views/index.jsx

Don't refer explicitly to conditions being amended since the open task probably hs nothing to do with conditions.
Also hide the link to update conditions if there is an open task since submitting the form will fail as a result of the open task.

Update message for PILs with an open task

---

pages/rops/update/schema/index.js

If a project has "other" species, then they must manually select all of the species in the ROPs, we don't pre-select any for them.

if other species are present, don't preselect any species

---

pages/rops/update/schema/index.js

* Updated disabling logic to use parent option, previously this was reverse engineered from the reveal children but has since been updated to use the parent field value

Bugfix - disabled rop options

---

pages/rops/procedures/list/formatters/index.jsx

When attempting to view the submitted ROP for "ROP with procedures" seed, it fails because `value` is undefined.
This is probably bad seed data but we should prevent it from breaking the page.

check value exists before attempting to use it

---

lib/validation/validators.js
pages/project-version/update/submit/index.js
pages/project-version/update/submit/schema/index.js
pages/task/read/routers/confirm.js
pages/task/read/views/components/ppl-declarations.jsx
pages/task/schema/confirm.js

This PR fixes two issues:
1. Legacy PPL amendments submitted by non-PELH/HOLCs were not correctly capturing the legacy AWERB text. This should now be captured correctly regardless of who submits the amendment.
2. PPL transfers were not asking the receiving establishment for their AWERB review date. We now force the receiving establishment to enter their AWERB review date (they cannot be exempt) and also add / review any Additional Availability AWERB dates

Legacy PPL / PPL transfer AWERB fixes

---

pages/task/read/routers/confirm.js

If the outgoing establishment for a PPL transfer declares themselves exempt from AWERB review, the `awerb-exempt` flag is set to `yes` on the task.
We don't re-ask the exemption question for the receiving establishment because the AWERB questions are now enforced, so it was never getting set to 'no'. This was causing the "Latest submission" section to render the "no-review-reason" even though the receiving establishment had to fill in the AWERB dates.
This fix sets it to 'no' when the receiving establishment endorses, so that all the AWERB dates are correctly played back in the "Latest submission" section of the task view.

Transfers must be AWERB reviewed by receiving establishment, flip the task flag

---

pages/rops/procedures/schema/index.js

The other procedure sub-purpose fields have the hint disabled to avoid saying "Select all that apply" on a radio group. Do this for basic sub-purposes too.

Hide hint message on basic sub-purposes for procedures

---

package-lock.json
package.json
pages/common/content/index.js
pages/rops/procedures/content/index.js
pages/rops/procedures/index.js
pages/rops/procedures/list/content/index.js
pages/rops/procedures/list/index.js
pages/rops/procedures/list/views/index.jsx
pages/rops/submit/views/index.jsx
pages/task/read/content/rop.js

Issue 2: ...a heading that says 'Latest return', please can this be changed to 'Return of procedures' 
Issue 3: ...a green banner pops up saying 'Return updated' ... Please remove.
Issue 4: ...content that says 'Add procedures completed in 2021' - please can we add a full stop 
Issue 5: ...a heading that says 'Submit this project's completed return of procedures' - please can we add a full stop
Issue 6: ...show empty procedures table
Issue 7: ...rops reporting add "Home" breadcrumb

Various ROPS fixes

---

pages/task/read/content/project.js
pages/task/read/views/components/establishment-links.jsx
pages/task/read/views/models/project.jsx

This is no longer appropriate since inspectors don't have specific establishments. Revert to a bulleted list with no accompanying preamble.

Remove "consultation required" text from PPL tasks with AA

---

pages/establishment/formatters/index.jsx
pages/establishment/read/content/index.js
pages/establishment/read/views/index.jsx
pages/establishment/update/content/fields.js
pages/establishment/update/routers/confirm.js
pages/establishment/update/schema/index.js
pages/task/read/content/establishment.js

This field was deprecated, but is now needed for ROPs data segmentation, so is restored.

Add UI to edit country field

---

pages/rops/update/views/components/confirm.jsx

Because we now link to the ROPs confirm page as standard it's possible to have selected purposes and no subpurposes, and return to the page. This means it needs to be able to render if the sub-purposes are `null`.
Default all instances of maybe-arrays before we map on them.

Don't map non-existent arrays in ROPs confirm page

---

pages/project/formatters/index.jsx

The project list was sharing code with the task view for generating a list of establishments, which caused it to break unexpectedly when the task view changed.
Restore the old formatter as a standalone component for use here.

Restore old inline establishment list functionality

---

pages/rops/update/schema/index.js

`purposes` is either an array or null, so we need to default it if it is null.

Default purposes to an empty array

---

pages/task/list/router.js
pages/task/list/views/table.jsx
pages/task/list/views/tasklist.jsx

The `updatedAt` column now shows the correct label when the status is filtered to completed tasks.
This also fixes an issue with "My tasks" status not rendering as selected by default.

updatedAt column header now correctly renders "Completed" when filtering completed tasks

---

pages/rops/procedures/list/content/index.js
pages/rops/procedures/list/formatters/index.jsx
pages/rops/procedures/schema/index.js
pages/rops/update/content/index.js
pages/rops/update/schema/index.js
pages/rops/update/views/components/confirm.jsx

~Needs https://github.com/UKHomeOffice/asl-schema/pull/525 merging and then bumping in `public-api` and `resolver`~
We don't currently have any ROPs on prod using `toxicity-other-lethal` so I've renamed it to `other-toxicity-lethal` for consistency with the other "other" fields.

Add reveal and playback of multi-input when toxicity-other-lethal selected

---

pages/task/read/routers/read.js
pages/task/read/views/components/activity-log.jsx

The previous links were using the establishment id from the task, which changes when the transfer task is handed over to the receiving establishment, which breaks the links (the existing project & version is not at the new establishment).
This PR changes the log to use the establishment from the model data in the activity event itself, which should always be the correct establishment.
Once a transfer is granted, some users will be able to view the new project / version at the receiving establishment, and for those users (receiving admins, applicant, ASRU) we link to that version. For users that can see the task but not the new version (e.g. outgoing admins) we link them to the final version at their establishment with the "transferred out" banner.

fix the links for previous PPL versions in the activity log

---

pages/project/update-licence-holder/routers/update.js
pages/project/update-licence-holder/views/index.jsx

This field wasn't being correctly mapped to a boolean when it was submitted, in the same way as the equivalent question for non-training PPLs was.
Add it to the ignore list for having an extra hidden field (used for RTE inputs) and map `'true'` to `true` in the `process` middleware.

Fix normalisation of previous training course question

---

pages/rops/update/schema/index.js

The "default" option should come first, as per the rest of the questions.

Reorder options for GA and new genetic line questions

---

pages/task/list/content/index.js
pages/task/list/views/tasklist.jsx

As well as applications, amendments and transfers we also want to include revocations.

Include revocations in available task filter options

---

pages/common/routers/datatable.js

If there is a comma in the value then it already gets wrapped in double quotes, so wrapping it again in `="..."`causes it to break in new and exciting ways.

Don't wrap csv values with commas

---

pages/pil/unscoped/courses/formatters/index.jsx

Where we show the details of a PIL-E then make the licence number a link to the PPL page so that it can be reviewed if needed. Specific need for this is in task pages, but it has value elsewhere that this component is used.

Make PPL number playback in PIL-E summary a link

---

package-lock.json
package.json
pages/task/list/content/index.js
pages/task/list/formatters/index.jsx

* Adds a countdown for PPL applications with a continuation where there is a date provided
* Falls back to the old `Includes project continuation` if it's an old task with unstructured data, or the user has not entered a date
* Is based on the earliest continuation date if there are multiple
* Show a "done" message once the PPL application is resolved

Show task list countdown components for continuations

---

pages/place/formatters/index.jsx

There are test assertions that expect the output here to be in a specific and consistent order, so fail occasionally de to database insertion ordering.
Make sure roles are always listed alphabetically.

Sort named people assigned to places in form playback

---

pages/project-version/read/js/index.js
pages/project-version/update/js/index.js
pages/retrospective-assessment/update/js/index.js

This is required to do key-value mapping of training module names in the training sections

Pass static content to project state initialisation

---

pages/project/read/views/sections/downloads.jsx

Only the granted version is accessible at AA establishments, so don't provide download links for superseded or in-progress amendment versions.

Hide download links for other versions when viewing at AA est

---

pages/rops/helpers.js

In order to not break when changing species after entering procedures, preselected species in the species selector now send their value to the server. This includes species that are preselected because they are listed on the PPL.
This means that the same species can end up included in the list of species loaded from the PPL as well as in the list of manually added species.
To prevent these appearing twice, call `uniq` on the set of returned species.

Ensure species list in ROPs is unique

---

pages/rops/update/views/components/endandered.jsx
pages/rops/update/views/components/ga.jsx
pages/rops/update/views/components/reuse.jsx
pages/rops/update/views/components/species.jsx

For questions relating to GA animals, re-use and endangered animals it is not possible to reliably determine the authorisation or otherwise on the project for legacy licences so these are showing up incorrectly as not authorised in some cases.
Hide all playback of values for legacy PPLs to avoid this.

Remove playback component in ROPs for legacy PPLs

---

pages/project-version/read/index.js

Inspectors were reporting concern that they could see their comments embedded in the licence when previewing it.

Hide comments in PPL preview view

---

pages/rops/update/confirm/index.js

This was falling through to a later router which was overwriting `res.locals.model` and resulting in an error loading the header component on this page.
Terminate response in this router to prevent fall-through.

Send response immediately in ROPs confirm update router

---

pages/profile/read/views/profile.jsx

A project with an open amendment to _add_ an additional establishment was showing on the user's profile as having additional availability already even though the amendment had not been granted.

Filter AA to only active on profile pages

---

pages/common/assets/sass/style.scss
pages/rops/procedures/list/formatters/index.jsx

Setting a width (or min/max-width) on the table cell itself doesn;t work because once the table is wider than it's container it will always attempt to reduce the width of all columns as far as possible.
This means we need to set a fixed width on a child element of the column in order to restrict how far the table can reduce the width of the column once we allow the text to break onto new lines.

Add fixed width to notes columns in procedures list

---

constants/index.js
pages/project/read/views/components/rops.jsx

For the early part of the year the previous year's ROPs are likely the most pertinent for a user, so allow the previous year to be considered "active" on the project landing page so that expanded content is available.

Allow previous year to remain "active" in project landing page ROPs section

---

pages/project/read/views/components/rops.jsx
pages/project/read/views/components/rops.spec.jsx

* Don't show any year's ROP until after the 1st February of that year.
* Fix bug where 2021 ROPs were not shown for projects that ended in 2021 - calculate per year if a ROP is applicable for that year, and display a message if no years are applicable.

Fix bugs with ROPs display for particular years

---

pages/project-version/index.js
pages/project-version/middleware/index.js

Comments are not being shown on PPL transfers because the code tries to find a task with a `grant` action to load comments from, and the task for a transfer has an action of `transfer`.
Allow comments to be loaded from transfers as well as applications and amendments.

Allow PPL transfers to display comments

---

pages/establishment/rops/index.js

Between January and June the default year will be the previous year's ROPs, but from July onwards default to the current year.

Make default year for establishment ROPs list dynamic

---

pages/project-version/update/endorse/views/index.jsx

The type property of the project under `static` was always undefined, and so the content always showed as an amendment.
Load the value from the correct location so applications display correctly.

Get project type from correct location on store

---

pages/task/read/content/project.js
pages/task/read/views/components/deadline.jsx
pages/task/read/views/models/project.jsx

Needs:
- https://github.com/UKHomeOffice/asl-workflow/pull/435
Any relevant deadlines are now displayed in the task status section, including project continuations if present.

Improvements to task deadlines in status header

---

pages/training/type/index.js

If a user starts adding a certificate, then cancels and adds an exemption then some fields are persisted on the certificate, which causes a schema validation error when submitting the exemption.
Reset the session values when submitting the form to choose between an exemption and certificate to avoid incorrect values being persisted.

Reset session values when adding an exemption

---

pages/task/list/content/index.js

Updating the task headings on the task view page had the knock on effect of also changing them in the task lists as the label was shared.
This returns the task list back to the shorter "PIL/PPL application" labels.

Go back to short labels for the task list

---

pages/task/content/status.js
pages/task/content/tasks.js
pages/task/list/formatters/index.jsx
pages/task/list/router.js
pages/task/middleware/rop-status.js
pages/task/read/routers/read.js
pages/task/read/views/components/activity-log.jsx
pages/task/read/views/components/task-details.jsx
pages/task/read/views/components/task-status.jsx
pages/task/read/views/models/rop.jsx

We want to make ROP reopening tasks visible in task histories for projects.
* Add playback of the ROPs year in task lists and task details
* Add new content for `reopened` status
* Remove logic which remaps statuses of ROPs ~because this is now done in workflow decorator~ - UPDATE: map the statuses in a server middleware here instead.
* Hide message about ROP submission date on `reopened` tasks

Improvements to ROPs tasks

---

pages/project-version/update/endorse/routers/endorse.js

The `getValues` function in the form router does a recursive clone of `req.model` with possibly harmful characters removed from all strings. This results in a ~2x increase in the memory usage when `req.model` represents a PPL version since both the sanitised and unsantised versions are stored in memory.
Since the endorsement form does not require any of the version data to be available it can be removed from `req.model` in the form setup step, and so avoid cloning large PPL data objects in memory.

Remove version data from form model in PPL endorse form

---

pages/project-version/update/endorse/views/index.jsx

`model` doesn't refer to the project itself here, but a wrapper around the project with a `project` property that refers to the project. Use that `model.project` to read the title.

Fix PPL title on submission screen

---

pages/project/update-licence-holder/index.js

When changing the licence holder on a PPL we do an API call to load the profile of the recipient, but in the case of a basic user moving their PPL to a collaborator this API call can fail because they don't have visibility of the profile.
In that case look in the list of collaborators for the intended recipient and use the details from there.

Don't throw if changing licence holder on a PPL to a collaborator

---

pages/project-version/update/endorse/content/index.js
pages/project-version/update/endorse/routers/endorse.js
pages/project-version/update/endorse/views/index.jsx

When an admin is submitting a PPL application or amendment on behalf of another user then add a second section to the declaration to say that they have the permission of the PPL holder to make the submission.
Also fixes a bug where the endorsing admin at the receiving establishment of a transfer was not shown endorsement declarations.

Update endorsement content if submitting on behalf of another user

---

pages/pil/dashboard/views/index.jsx

The "Discard draft application" link is actually a button that triggers a confirm dialogue which then submits a form.
If the user was quick enough, they could accept the dialogue and then click the button again - the previous submit request will have already been processed and the second attempt will fail because the PIL no longer exists to be deleted.
Prevent the discard button from being clicked again if the form has been submitted.

Prevent the discard button from being activated more than once

---

pages/project-version/nts/views/components/ra-summary.jsx

If someone has started an RA but not entered _any_ input into any field then the `data` is null, and attempts to read properties from it throws an error.

Default to empty data in draft RA

---

pages/project-version/pdf/index.jsx

The value is a string, so was being set to true always, even when `draftRa=false` was passed as the query string. This resulted in the RA values being incorrectly read when `draftRa=false` was set on a non-draft RA.

Correctly read `draftRa` from query string

---

package-lock.json
package.json

https://github.com/advisories/GHSA-wm7h-9275-46v2 is blocking our builds on https://github.com/UKHomeOffice/asl-internal-ui due to a vulnerability in `dicer`.
Bumping `multer` (used by the form middleware) to at least `^1.4.5-lts.1` should resolve this.
More info: https://github.com/expressjs/multer/pull/1097

bump multer to fix CVE-2022-24434

---

pages/rops/helpers.js

The `getSpecies` function removes any `other-*` values and replaces them with the free text, so wasn't catching `other-nhps` as being an NHP return.
If `other-nhps` is used then return true straight away.

Show NHPs questions if user has selected `other-nhps`

---

pages/task/read/routers/confirm.js

If the status of the task is no longer available on the session then building the schema fails with an error. Instead redirect back to the task page and allow the user to recommence the journey.

Redirect task confirmation page if session is expired

---

pages/project-version/docx/index.js

S3 images use a `token` property and not a `src` so need to build the URL from that instead of trying to process the `src` property which doesn't exist.

Update word document rendering for new image formats

---

pages/task/read/views/components/task-details.jsx

If a user has a PPL or a named role but no longer has an active PIL, then `profile.pil` will not exist and so profile update tasks throw errors.

Don't throw error on profile updates for non-PIL-holders

---

pages/common/middleware/index.js
pages/establishment/dashboard/index.js
pages/establishment/index.js
pages/establishment/pdf/index.jsx
pages/establishment/read/index.js

There is an API call to `GET /establishment/:id` on every page load, which was previously loading the establishment's named people even though these were only used in a small handful of places.
In order to speed up the API calls this has been removed from the API response and split into its own endpoint which is called only on the pages where the named people are needed - specifically the establishment landing page, details page, and PDF download.

Load named people only when needed

---

package-lock.json
package.json
pages/common/content/index.js
pages/project-version/components/project-status-banner.jsx
pages/project/content/index.js
pages/project/formatters/index.jsx
pages/success/content/index.js
pages/success/index.js
pages/task/content/status.js
pages/task/list/formatters/index.jsx
pages/task/read/content/base.js
pages/task/read/content/confirm.js
pages/task/read/content/refusal-notice.js
pages/task/read/content/review.js
pages/task/read/helpers/declarations.js
pages/task/read/index.js
pages/task/read/routers/confirm.js
pages/task/read/routers/index.js
pages/task/read/routers/read.js
pages/task/read/routers/review.js
pages/task/read/routes.js
pages/task/read/views/components/activity-log.jsx
pages/task/read/views/components/refusal-notice-warning.jsx
pages/task/read/views/components/refusal-notice.jsx
pages/task/read/views/components/task-status.jsx
pages/task/read/views/confirm.jsx
pages/task/read/views/review.jsx

For project applications, the "rejected" option is now replaced with an "Notify of intention to refuse" which returns the application to the applicant and starts a 28 timer before the project can actually be refused. The full refusal notice is displayed in the task activity log.
Once the timer expires, the application can be refused by an inspector regardless of who the application is currently with. Refused projects will display a red banner on their landing page informing of the project status and the date when the project was refused.

Feature: refuse a project application

---

pages/project-version/middleware/index.js

The named people are no longer automatically included in the response for an establishment so need to be loaded separately when viewing a PPL.

Load PEL holder information when viewing a PPL version

---

pages/task/read/routers/confirm.js

The condition was checking the value of `returnTo`, but then redirecting to `values.returnTo` which is undefined, and so was redirecting to a URL that threw a 404.
Bug was introduced [here](https://github.com/UKHomeOffice/asl-pages/commit/831b11ebf2c9f8ed28326c8223a8015e29286167#diff-3eb53d7029005013e62eefa22e319f2cdcd923f1ba4861db5a7e12c3e3b6b9b7L73-R61)

Fix redirects to open task

---

pages/pil/dashboard/index.js
pages/pil/training/index.js

This now stores the `Do you need to update this training record?` answer on the training page on the task as: `"training": {"update": false}`
This then allows the edit and resubmit page to use this to display the training summary and completed status label rather than the answer in the session.

ASL-2017 - Save PIL training answer on task

---

pages/common/assets/sass/style.scss

Edit species list css to add bullet points

---

pages/common/content/index.js
pages/task/read/routers/confirm.js

The the user tries to submit a task with a status that is no longer valid (i.e. it's been processed in another tab etc so the target status doesn't apply anymore) then redirect back to the task with an error notification rather than leaving the user on an error page.

Redirect to task page with error message if processing fails

---

pages/project-version/docx/index.js

- Only attempt to load images which are PNG or JPEG files
- All other image types load an error message

Add error message for unsupported image types

---

pages/project-version/middleware/index.js

This will allow path to reference objects with UUID as property keys for diff comparison, for example:
The path `reusableSteps.8656ff4b-fd16-4c60-9cd8-eb72dcd26989.title` should work on the following JSON structure
`
{
"reusableSteps": {
"8656ff4b-fd16-4c60-9cd8-eb72dcd26989": {
"title": "some title",
...
}
}
}
`

ASL-4046 - Allow retrieving a node by path within an object by UUID

---

pages/task/list/components/assign-task.jsx

Give 'unassigned' block formatting so it stays on its own line no matter how big the table cell is

Add block class to fix formatting in larger table

---

lib/validation/validators.js
pages/profile/content/index.js
pages/profile/invite/schema/index.js

There wasn't any before, for reasons unknown, and it resulted in downstream errors sending invitation emails.

Add email validation to the invite user form

---

pages/place/routers/confirm.js

Conditions and reminders data from the task was being sent to public-api as part of the place amendment which was causing an error as it is not whitelisted
Stop sending conditions and reminders data from the task

ASSB-1258: Fix resubmission of place amendments

---

pages/task/read/views/models/establishment.jsx
pages/task/read/views/models/place.jsx
pages/task/read/views/models/role.jsx

Previously when a condition was removed it would load the condition that is saved to the establishment, rather than a blank condition as the conditional would be negative because taskData.condition was blank.
Adds the establishment condition to the task data if there is not one on the task and always loads the condition from the task, fixes issue.

Fix default condition appearing when condition is removed from task

---

.drone-1.0.yml
.npmrc
package-lock.json
package.json

https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4304
Lenny's creds no longer work for publishing to artifactory npm. This replaces his credentials with one provided by ACP.

Update npmrc to use new artifactory token

---

pages/project/read/views/components/current-version.jsx
pages/project/read/views/sections/downloads.jsx
pages/task/read/routers/confirm-hba.js
pages/task/read/views/components/activity-log.jsx
pages/task/read/views/confirm-hba.jsx
pages/task/read/views/confirm.jsx
pages/task/read/views/upload-hba.jsx

Adds hba filename as suggested download title on hba download links
**Suggested download title matches upload title**

[ASL-4299] use hba filename

---

package-lock.json
package.json
pages/project/read/views/index.jsx

There looks to be a race condition where:
```mermaid
flowchart LR
A[User clicks on tab] --> B[onClick updates active tab] 
B --> C[Rerender triggers onEffect setting active tab to current hash]
A --> D[Default link behaviour updates URL hash]
```
If the URL hash update happens after the onEffect then the active tab ends up being the old one.
This change addes the location to the dep array so when the hash is updated the onEffect is run again. It can cause a slight flicker where the browser renders new tab -> old tab -> new tab in quick succession, but that only happens when the race condition actually occurs and is better than the tab not changing.

Fix flaky tab navigation

---

pages/pil/unscoped/list/schema/index.js
pages/project/schema/index.js

https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1385
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1386
There were two CSV schemas using moment to format dates using date-fns format strings. `d` is day of month in date-fns and numerical day of week in moment.js, so this was showing 0-6.
Switched to using date-fns.

[ASSB-1385] Use date-fns when formatting dates using constant formats

---

package-lock.json
package.json

Keycloak Realm now using lower case, Keycloak URL now using V22 instance URI, mocha also updated.

Keycloak V22
