pages/establishment/tests/middleware.js, pages/place/tests/middleware.js, test/functional/app/index.js, test/functional/fixtures/index.js, test/functional/helpers/pages.js
This lets a page do setup to configure any request parameters that it might expect to have been set upstream.
=> Allow mounting an optional middleware on functional tests

pages/common/routers/confirm.js, pages/place/index.js, pages/place/routers/add-or-edit.js
* Updated to redirect to referrer on edit/add cancel
TODO: revisit routing and paths - provide a manifest in implementations
=> Redirect to list page on edit/add cancel

pages/common/routers/confirm.js, pages/common/views/components/form.jsx, pages/common/views/components/model-summary.jsx, pages/place/content/errors.js, pages/place/content/fields.js, pages/place/update/views/confirm.jsx
* Added declaration checkbox to edit and add confirm pages
* Added placeholder error message - to be updated by content designer
=> Added declaration box

pages/profile/content/index.js, pages/profile/list/content/index.js, pages/profile/list/schema/index.js, pages/profile/list/views/index.jsx
* Removes "licence type" column
* Adds a default value of `-` to PIL number column
* Changes search label
=> Content changes to profile list

package.json, pages/common/assets/sass/_forms.scss, pages/common/assets/sass/style.scss, pages/common/views/components/form.jsx, pages/common/views/containers/form.jsx, pages/place/content/fields.js, pages/place/create/content/index.js, pages/place/create/index.js, pages/place/delete/content/confirm.js, pages/place/delete/content/index.js, pages/place/delete/index.js, pages/place/delete/views/index.jsx, pages/place/routers/amend.js, pages/place/update/views/confirm.jsx
* added field to schema on amend pages
* show on confirm page if present
* added textarea field type to form
* added 100% width to textarea
=> Added comments box

pages/common/assets/sass/_datatable.scss, pages/common/assets/sass/_filters.scss, pages/common/assets/sass/style.scss, pages/common/content/index.js, pages/common/views/components/controls.jsx, pages/common/views/components/filters.jsx, pages/place/list/content/index.js, pages/place/list/views/index.jsx
* updated label for creating a new place
* updated label for editing
* reduced width of controls in expandable column
* Made filters collapsible
=> Design edits to places list

pages/common/assets/sass/_forms.scss, pages/common/assets/sass/style.scss, pages/common/routers/form.js, pages/common/views/components/conditional-reveal.jsx, pages/common/views/components/field.jsx, pages/common/views/components/form.jsx, pages/common/views/components/inset.jsx, pages/common/views/containers/diff.jsx, pages/common/views/containers/form.jsx, pages/place/content/fields.js, pages/place/create/content/confirm.js, pages/place/create/index.js, pages/place/index.js, pages/place/routers/amend.js, pages/place/schema/index.js, pages/place/update/content/confirm.js, pages/place/update/content/index.js, pages/place/update/index.js, pages/place/update/views/confirm.jsx, pages/place/update/views/index.jsx
* added conditional reveal component
* added restrictions when editing a room
* fixed bug with persisting data - Object.assign not merge
=> Feature - restrictions

pages/common/assets/sass/_datatable.scss, pages/project/list/content/index.js, pages/project/list/views/index.jsx
* removed green and orange status colours
* added snippet for 3 or more months left
* updated snippet for search box
* updated label for project title
=> Design changes to projects list

pages/place/create/index.js, pages/place/delete/index.js, pages/place/update/index.js
Sends the form values to the API following a completed addition, amendment or deletion of a schedule of premises item.
=> Submit form data to API following amendment submission

pages/common/assets/sass/style.scss, pages/common/views/components/accordion.jsx, pages/profile/view/content/index.js, pages/profile/view/tests/index.js, pages/profile/view/views/index.jsx, test/functional/fixtures/profile.json
* added NACWO training section if profile is a NACWO and qualification not null
* added projects if PPL holder
* added accordion component
* fixed accordion bug when only one child
=> Profile page amends

lib/middleware/csrf.js, package-lock.json, package.json, pages/common/content/index.js, pages/common/routers/form.js, pages/common/views/components/form.jsx, pages/common/views/containers/form.jsx, pages/place/delete/views/index.jsx, pages/place/tests/index.js, pages/place/update/views/confirm.jsx
* added csurf lib
* added csrf middlware if env != test
* added hidden input to form and confirm pages
=> Added CSRF checking

pages/place/routers/confirm.js, pages/place/tests/index.js
* amended stale session redirect to handle urls with query params.
* added tests
=> Fixed session state redirect bug

lib/utils/index.js, package-lock.json, package.json, pages/common/routers/datatable.js, pages/common/routers/form.js, pages/place/create/index.js, pages/place/index.js, pages/place/tests/index.js
* added striptags library
* added helper to parse string values in model and strip html tags
=> Bugfix - strip html tags from user input

lib/utils/index.js, pages/common/routers/form.js, pages/common/views/components/diff.jsx, pages/place/formatters/index.jsx, pages/place/update/views/confirm.jsx
* updated comparator to use lodash isEqual
* use accessor to compare id's for nacwo
=> Bugfix - nacwo showing as highlighted if not changed

lib/validation/index.js, pages/common/routers/form.js, pages/common/views/components/conditional-reveal.jsx, pages/common/views/components/form.jsx, pages/place/content/errors.js, pages/place/tests/index.js, pages/place/update/index.js, test/functional/fixtures/place.json
* updated form to persist conditional reveal values
* dont validate field if conditional reveal is set to false
=> Bugfix - persist conditional reveal values

pages/common/views/components/status-bar.jsx
Gets the name from the logged-in user's profile and links to their profile page.
=> Add link to profile page in header bar

pages/profile/content/index.js
=> Error messages

lib/validation/index.js, lib/validation/validators.js, pages/common/assets/sass/style.scss, pages/common/views/components/form.jsx, pages/common/views/layouts/default.jsx
Pass empty array to scripts if no scripts passed. We don't always want the common bundle
Bumped govuk-react-components
=> Added validator to check a field matches another given field

package-lock.json, package.json, pages/profile/invite/index.js, pages/profile/invite/views/index.jsx
Fixed bug with missing labels on role field
Added establishment name to invite page
=> Added breadcrumbs to invite page

pages/profile/content/index.js
Changed the order of Basic/Intermediate/Admin and the associated wording layout.
=> Permission wording to match latest thinking

pages/common/assets/sass/style.scss, pages/pil/dashboard/content/index.js, pages/pil/dashboard/index.js, pages/pil/dashboard/views/index.jsx, pages/pil/dashboard/views/training-data.jsx
=> Allow the removal of training from a pil application

pages/pil/certificate/content/index.js, pages/pil/certificate/index.js, pages/pil/certificate/schema/index.js, pages/pil/modules/index.js
The pass_date was not being saved due to the field name not matching the database column name.
There were a few other issues with validation that should now be resolved.
=> pass_date should now save correctly

lib/utils/index.js, pages/pil/dashboard/content/index.js, pages/pil/dashboard/index.js, pages/pil/dashboard/views/index.jsx, pages/pil/dashboard/views/procedure-data.jsx, pages/pil/dashboard/views/training-data.jsx, pages/pil/index.js, pages/pil/modules/index.js, pages/pil/procedures/content/index.js, pages/pil/procedures/content/procedure-definitions.js, pages/pil/procedures/index.js, pages/pil/procedures/schema/index.js, pages/pil/procedures/views/index.jsx
Allow the user to select which procedures they want their licence to cover.
This is just the UI side, it does not persist the data further than the current session.
=> AS-651: select procedures

package-lock.json
npm audit was complaining about vulnerabilities, so I ran the auto-fix.
=> Auto fix vulnerabilities

pages/common/assets/sass/style.scss, pages/common/views/components/application-confirm.jsx, pages/pil/application/content/index.js, pages/pil/application/views/application-confirm.jsx, pages/pil/application/views/exemption-data.jsx, pages/pil/application/views/index.jsx, pages/pil/application/views/procedure-data.jsx, pages/pil/application/views/training-data.jsx
Adds a confirmation checkbox once all the sections in the PIL are complete.
When the user ticks the checkbox, the submit button is displayed.
=> AS-653: submit PIL confirmation dialogue

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/common/views/components/application-confirm.jsx, pages/pil/application/content/success.js, pages/pil/application/index.js, pages/pil/application/views/success.jsx
This adds a redirect to the success page on submit of the PIL (doesn't actually update the PIL).
=> Success page for demo

pages/pil/application/index.js, pages/pil/application/views/index.jsx, pages/pil/application/views/procedure-data.jsx, pages/pil/application/views/success.jsx, pages/pil/index.js
This updates the PIL with a "submitted_at" time and (for now) prevents you from creating / editing a new PIL.
=> Submit the PIL application

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/common/views/components/application-confirm.jsx, pages/common/views/components/form.jsx, pages/common/views/containers/form.jsx, pages/pil/application/content/index.js, pages/pil/application/index.js, pages/pil/application/schema/index.js, pages/pil/application/views/index.jsx
* updated react components to get latest reveal code
* form can now have children
* simplified application confirm component - render a form
* added validation to check declaration checked and at least one procedure selected
=> Show submit button by default

lib/middleware/permissions.js, lib/page.js, pages/common/helpers/index.js, pages/common/routers/README.md, pages/establishment/dashboard/index.js, pages/establishment/dashboard/tests/middleware.js, pages/establishment/details/index.js, pages/pil/application/index.js, pages/pil/categories/index.js, pages/pil/exemptions/index.js, pages/pil/index.js, pages/pil/modules-exempt/index.js, pages/pil/modules/index.js, pages/pil/procedures/index.js, pages/place/create/index.js, pages/place/delete/index.js, pages/place/index.js, pages/place/list/index.js, pages/place/tests/middleware.js, pages/place/update/index.js, pages/profile/index.js, pages/profile/invite/index.js, pages/profile/list/index.js, pages/profile/list/tests/middleware.js, pages/profile/read/tests/middleware.js, pages/project/list/index.js, pages/project/list/tests/middleware.js
* Rename `req.establishment` -> `req.establishmentId`
* Rename `req.profile` -> `req.profileId`
=> AS-719: rename request properties that contain ids

pages/common/views/base.jsx, pages/feedback/content/index.js, pages/feedback/index.js, pages/feedback/views/index.jsx, pages/index.js
NOTE: ignored back link for now as this should be tackled for the entire app and not just this page
=> added temporary feedback page with link to email

pages/task/read/views/confirm.jsx, pages/task/read/views/index.jsx
These were causing an erroneous white background on the headings. Replace with the `<Header/>` component from `@asl/components`.
=> Remove wrapping `<header>` elements

pages/place/delete/views/index.jsx
Use the same components as the place amendment journey for removal to ensure the correct markup is applied.
=> Fix styling of form control in remove place journey

pages/pil/create/views/index.jsx
The old `<ul class="dashboard">` styles don't exist anymore so it was rendering weirdly.
=> Use `<PanelList/>` component for PIL start page

package-lock.json, package.json, pages/task/list/router.js, pages/task/list/views/tasklist.jsx
Also fixes api route for tasklist datatable
=> Bump components for datatable classes

pages/project/list/views/index.jsx
`profileId` had the wrong prop name.
=> AS-858: fix licence holder link in project list

pages/profile/permission/content/index.js
There were a couple of spelling mistakes.
=> Fix profile removal copy

pages/pil/training/content/modules.js
Phil Cox requested a wording change in the original ticket after the previous PR was merged, so fixing.
=> Change the wording on species selection

pages/pil/exemptions/routers/modules.js, pages/pil/procedures/index.js, pages/pil/training/routers/modules.js, pages/place/create/index.js, pages/place/update/index.js, pages/profile/invite/index.js, pages/profile/permission/index.js, pages/user/update/index.js
Pass data to be written to database consistently as `data` property on request body, and related metadata as `meta`.
=> Refactor API payloads

pages/common/content/index.js, pages/establishment/dashboard/views/index.jsx, pages/establishment/details/views/index.jsx, pages/profile/read/views/index.jsx
In places where we mention "Licence number" or "Licence holder", be clear about the type of licence.
=> AS-893: be more specific with licence wording

pages/common/routers/datatable.js
This allows dynamic replacement of the schema for a datatable, see: 
https://github.com/UKHomeOffice/asl-internal-ui/pull/40/files#diff-8fcd7a31470eb38e82be8f8cc7f5a094R30
=> Allow a datatable schema to be provided as part of the configure

package-lock.json, package.json, pages/pil/update/content/index.js, pages/pil/update/schema/index.js, pages/pil/update/views/index.jsx, pages/place/create/index.js, pages/place/routers/confirm.js, pages/place/schema/declarations.js, pages/place/update/content/confirm.js, pages/place/update/content/success.js, pages/place/update/index.js, pages/place/update/views/confirm.jsx, pages/place/update/views/success.jsx, pages/profile/roles/content/confirm.js, pages/profile/roles/content/index.js, pages/profile/roles/content/success.js, pages/profile/roles/routers/confirm.js, pages/profile/roles/schema/declarations.js, pages/profile/roles/views/confirm.jsx
Use the same component for all our confirm pages.
=> Integrate ApplicationConfirm component into confirm pages

pages/pil/update/content/index.js
The tests are expecting a certain label, this will fix it.
=> Submit button label did not get updated with switch to ApplicationConfirm

pages/common/content/index.js, pages/profile/read/content/index.js, pages/profile/read/views/index.jsx, pages/profile/read/views/role-apply.jsx, pages/profile/read/views/role-remove.jsx, pages/profile/roles/apply/content/confirm.js, pages/profile/roles/apply/content/index.js, pages/profile/roles/apply/content/success.js, pages/profile/roles/apply/index.js, pages/profile/roles/apply/views/confirm.jsx, pages/profile/roles/apply/views/index.jsx, pages/profile/roles/apply/views/success.jsx, pages/profile/roles/index.js, pages/profile/roles/remove/content/confirm.js, pages/profile/roles/remove/content/index.js, pages/profile/roles/remove/content/success.js, pages/profile/roles/remove/index.js, pages/profile/roles/remove/views/confirm.jsx, pages/profile/roles/remove/views/index.jsx, pages/profile/roles/remove/views/success.jsx, pages/profile/roles/routers/confirm.js, pages/profile/roles/routers/success.js, pages/profile/roles/schema/declarations.js, pages/profile/roles/schema/index.js, pages/profile/roles/views/confirm.jsx
Adds the UI for removing named roles from people.
Refactored the routers / views to be consistent with the expected locations for pages.
=> Remove a named role ui

pages/task/list/content/index.js, pages/task/list/router.js, pages/task/list/views/tasklist.jsx
And pass tab selection through to downstream api calls
=> Add optional tabs to tasklist component

pages/pil/training/routers/modules.js, pages/pil/training/views/modules.jsx
These changes got included when I bumped @asl/service in https://github.com/UKHomeOffice/asl-pages/commit/02ec1fc27fb044b446a12c15e9ef65f22f47e8ea, reverting.
=> Revert accidental changes to modules

pages/pil/training/views/modules.jsx
The styles are out of whack right now
=> Fix modules page header component

pages/common/content/index.js, pages/profile/index.js, pages/profile/permission/content/index.js, pages/profile/permission/index.js, pages/profile/read/index.js
Success notifications are now displayed when changing or removing permissions. (AS-865)
The current permission level should already be selected on the edit permissions form. (AS-864)
A breadcrumb back to the profile should now appear on the edit perms page.
=> Permission notifications

package-lock.json, package.json, pages/pil/training/content/modules.js, pages/pil/training/views/modules.jsx
Waiting on https://github.com/UKHomeOffice/asl-components/pull/31
=> Allow removal of species selects in modules

pages/task/read/routers/view.js
The deep object access was fragile and was throwing errors. Replace with a `get` to fall back gracefully if properties are missing.
=> Use lodash get for object access

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/task/read/views/confirm.jsx
Move the link to sit alongside the submit button instead of above it.
=> Move change link on task action confirm pages

constants/index.js, pages/pil/content/index.js, pages/pil/procedures/schema/index.js
Also refactor to keep PIL related content closer to PIL code. It had no business being thrown out into the constants.
=> Fix spelling of "neuromuscular"

pages/profile/read/index.js, pages/profile/read/views/index.jsx, pages/profile/read/views/profile.jsx
All users should be able to apply for a pil for themselves.
=> Fix missing pil apply button

pages/profile/read/content/index.js, pages/profile/read/views/index.jsx, pages/profile/read/views/profile.jsx
* Restore remove named role button
* Use standard header component in profile view page
* Standardise call-to-action controls and styling
* Remove link to establishment
=> Fix profile component bugs

pages/profile/read/views/profile.jsx
We use the array length as a condition which casues react to render a zero when then condition is false because it's not a boolean. Add a `!!` to the length to cast it to a boolean.
=> Cast array length to boolean

pages/common/helpers/index.js, pages/place/update/views/confirm.jsx, pages/task/read/routers/view.js, pages/task/read/views/place.jsx, pages/task/read/views/role.jsx
* Add to the `getEstablishment` helper function to parse out pelh and nprc
* Wrap all references to PELH in conditionals so that they don't blow up if it's missing.
=> Handle missing PEL holders

pages/project/read/index.js, pages/project/read/views/index.jsx
Prevents displaying the amend project button to users who are not able to amend the project
=> Check for update permissions on a project

pages/profile/read/content/index.js
Makes empty states work for views.
=> Removed you

pages/common/content/index.js
Licensed premises should be referred to as Approved area(s)
=> Approved area

pages/profile/roles/remove/content/index.js
With the proper process this time :-)
=> Clearing up page titles

pages/profile/read/views/index.jsx, pages/profile/read/views/profile.jsx
Contact details are not a per-establishment thing, so just show them at the top.
DOB will only show if the user is viewing their own profile.
=> Move contact details / dob to top of page

pages/project/content/index.js, pages/task/read/content/project.js, pages/task/read/views/project.jsx
=> Only show declarations when with inspectorate, rename button

pages/task/read/views/activity-log.jsx
Also stops the toggle link jumping to the top of the page.
=> Prevent missing subject from breaking activity log

pages/establishment/details/content/index.js, pages/establishment/details/views/index.jsx
The key in data is `procedure` not `procedures`.
=> Fix key for licensed procedure establishments

pages/pil/exemptions/content/modules.js, pages/pil/update/content/index.js, pages/task/read/content/pil.js
A few things I could change myself. Mostly removing 'you' wherever necessary.
=> PIL amendment content amends

pages/pil/exemptions/content/modules.js, pages/task/content/status.js
Not many changes here.
It would be good to have an additional  action of 'Amend licence' for the Approved state for amendments.
I'm also unsure what Incomplete, Case opened and Case updated are. Will these appear as labels in a task list?
=> Changes to task statuses and actions

pages/task/read/routers/view.js
Requires https://github.com/UKHomeOffice/asl-workflow/pull/97 to be merged first.
=> Use the model from the task rather than attempting to fetch a potentially deleted model

pages/common/content/index.js, pages/pil/create/index.js, pages/pil/exemptions/index.js, pages/pil/index.js, pages/pil/procedures/index.js, pages/pil/read/index.js, pages/pil/training/index.js, pages/pil/update/index.js, pages/place/create/index.js, pages/place/delete/content/confirm.js, pages/place/delete/content/index.js, pages/place/delete/index.js, pages/place/tests/index.js, pages/place/update/index.js, pages/profile/index.js, pages/profile/invite/index.js, pages/project/index.js, pages/project/read/index.js, pages/task/read/routers/view.js
This PR relies on code in  https://github.com/UKHomeOffice/asl-components/pull/49 so that should be merged first and then I'll need to bump the components version.
=> Fix the breadcrumbs

pages/pil/training/schema/certificate.js, pages/pil/update/views/index.jsx, pages/task/read/views/pil.jsx
Also removes the rando dots in the example date input because they're not a thing.
=> Use longhand date formats when replaying dates

package-lock.json, package.json, pages/common/content/index.js, pages/project-version/read/index.js, pages/project-version/read/views/index.jsx
This encapsulates all of the logic for whether to render a banner or not inside the banner component itself rather than including it in each page. This brings the project version instance inline with the other pages which do not include custom logic in the page.
=> Pass version to licence status banner component

pages/profile/roles/apply/content/confirm.js
As per https://jira.digital.homeoffice.gov.uk/browse/AS-1478.
=> Declaration content added

lib/middleware/permissions.js, lib/validation/index.js, lib/validation/validators.js, package-lock.json, package.json, pages/common/content/index.js, pages/common/content/success-messages.js, pages/common/routers/form.js, pages/place/routers/amend.js, pages/project/index.js, pages/project/read/views/index.jsx, pages/project/update-licence-holder/content/confirm.js, pages/project/update-licence-holder/content/index.js, pages/project/update-licence-holder/index.js, pages/project/update-licence-holder/routers/confirm.js, pages/project/update-licence-holder/routers/update.js, pages/project/update-licence-holder/schema/declaration.js, pages/project/update-licence-holder/schema/experience-fields.js, pages/project/update-licence-holder/schema/index.js, pages/project/update-licence-holder/views/confirm.jsx, pages/project/update-licence-holder/views/index.jsx, pages/project/update-licence-holder/views/success.jsx, pages/task/read/content/project.js, pages/task/read/routers/view.js, pages/task/read/views/project.jsx
* added pages for PPL holder update journey
* added task content
* bumped projects and components
=> Amend PPL Holder

pages/establishment/update/index.js
This should fix the authorisation checkbox bugs:
* https://jira.digital.homeoffice.gov.uk/browse/AS-1601
* https://jira.digital.homeoffice.gov.uk/browse/AS-1602
=> Fix checkbox unticking

pages/common/content/index.js, pages/profile/content/fields.js, pages/profile/read/content/index.js, pages/profile/roles/apply/content/confirm.js, pages/profile/roles/apply/content/index.js, pages/profile/roles/remove/content/index.js
Content changes from tickets AS-1487 and AS-1351.
Let me know if this causes any issues with anything.
=> Text changes

pages/establishment/update/content/fields.js, pages/place/content/fields.js, pages/task/read/content/base.js, pages/task/read/content/establishment.js, pages/task/read/content/place.js, pages/task/read/content/profile.js
Again, let me know if any of this doesn't work or breaks any tests.
=> Afternoon content amends.

pages/project/update-licence-holder/routers/update.js
We were limiting to 100 profiles, pass limit: all to astop this happening
=> Dont limit profile list

pages/task/read/content/base.js
After feedback, we have switched things around in this hint text.
=> Minor amend

pages/task/read/views/activity-log.jsx, pages/task/read/views/deadline.jsx, pages/task/read/views/project.jsx
The deadline was being calculated base don initial submission, and not being reset if resubmitted.
The activity log was showing "With inspectorate" as the action for a deadline extension.
https://jira.digital.homeoffice.gov.uk/browse/AS-1609
https://jira.digital.homeoffice.gov.uk/browse/AS-1616
=> Fix PPL deadline bugs

pages/common/content/success-messages.js
=> Minor content changes

pages/common/assets/sass/style.scss, pages/profile/read/views/profile.jsx
Makes a few requested design changes to the profile that gets embedded in the user's dashboard.
=> Clean up profile view for dashboard

pages/common/content/index.js, pages/common/content/success-messages.js, pages/common/routers/success.js, pages/pil/index.js, pages/pil/read/content/index.js, pages/pil/read/views/index.jsx, pages/pil/revoke/content/confirm.js, pages/pil/revoke/content/index.js, pages/pil/revoke/index.js, pages/pil/revoke/routers/confirm.js, pages/pil/revoke/routers/update.js, pages/pil/revoke/schema/index.js, pages/pil/revoke/views/confirm.jsx, pages/pil/revoke/views/index.jsx, pages/pil/revoke/views/success.jsx, pages/profile/read/views/profile.jsx, pages/task/content/status.js, pages/task/read/content/pil.js, pages/task/read/routers/view.js, pages/task/read/views/pil.jsx
* Added revoke routes inc confirm and success
* Added content for revocation tasks
* Added content for some success messages
=> Revoke PIL

pages/project/read/views/index.jsx
Missed this button when I fixed the previous one :/
=> Need a link for drafts as well

pages/common/content/index.js
Change to feedback email address in BETA banner. As requested by Martin W
=> Email change

pages/establishment/update/content/fields.js, pages/place/content/fields.js, pages/project/update-licence-holder/content/index.js
As per https://jira.digital.homeoffice.gov.uk/browse/AS-1696
=> Minor text changes

pages/task/read/content/base.js, pages/task/read/content/extend.js, pages/task/read/content/project.js
As per https://jira.digital.homeoffice.gov.uk/browse/AS-1696
=> Content changes

pages/pil/exemptions/routers/modules.js, pages/pil/helpers/species.js, pages/pil/modules/content/index.js, pages/pil/modules/views/index.jsx
Also fixed (normalised) the field ids for the "reason" reveals in exemptions.
=> Add "other species" text input when other is selected

pages/common/components/in-progress-warning.jsx, pages/common/content/success-messages.js, pages/establishment/details/content/index.js, pages/pil/read/content/index.js, pages/profile/permission/content/index.js, pages/project/read/views/index.jsx
=> Content amends

lib/utils/index.js
`import` should only be used in jsx files.
=> Swap import for require

package-lock.json, package.json, pages/common/content/index.js, pages/profile/invitations/content/index.js, pages/profile/invitations/views/index.jsx
Waiting on https://github.com/UKHomeOffice/asl-components/pull/78
=> ExpiryDate component now passes a unit to the snippet

pages/task/read/views/project.jsx
Also, don't show the "ready" declaration for amendments.
=> Don't show the deadline if the task is an amendment

pages/place/list/index.js
These should sort by site first, and not database order.
=> Add a default sort order to places list

pages/task/read/views/deadline.jsx, pages/task/read/views/project.jsx
Waiting on https://github.com/UKHomeOffice/asl-workflow/pull/130
=> Hide deadline extend button on closed tasks

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/project-version/read/views/index.jsx
* Added container for status message
* Bumped projects
=> Project conditions syncing

package-lock.json, package.json, pages/common/content/index.js, pages/profile/invitations/content/index.js, pages/task/list/views/tasklist.jsx, pages/task/read/views/deadline.jsx, pages/task/read/views/project.jsx
Also moved deadline calc to workflow decorator
=> Display time left until deadline on tasklist

pages/project/formatters/index.jsx
Same deal as internal-ui but missed this one for external users.
=> Only show countdown on projects list if less than 12 months

pages/profile/roles/apply/content/index.js, pages/profile/roles/remove/content/confirm.js, pages/profile/roles/remove/content/index.js
The titles shouldn't be "Amend profile" because that's not what is happening.
=> Fix titles for named role addition/removal

pages/profile/content/fields.js
=> Content update

package-lock.json, package.json, pages/common/content/index.js, pages/common/content/success-messages.js, pages/pil/revoke/content/confirm.js, pages/pil/revoke/content/index.js, pages/project/index.js, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/index.jsx, pages/project/revoke/content/confirm.js, pages/project/revoke/content/index.js, pages/project/revoke/index.js, pages/project/revoke/routers/confirm.js, pages/project/revoke/routers/revoke.js, pages/project/revoke/schema/index.js, pages/project/revoke/views/confirm.jsx, pages/project/revoke/views/index.jsx, pages/project/revoke/views/success.jsx, pages/task/read/content/base.js, pages/task/read/views/project.jsx
~Waiting on https://github.com/UKHomeOffice/asl-public-api/pull/173~
=> Revoke a PPL

package-lock.json, package.json, pages/common/content/index.js
Currently it shows "Expired" which is not correct
=> Show "Expires today" for countdown if a licence expires today

pages/establishment/details/content/index.js
As per https://jira.digital.homeoffice.gov.uk/browse/AS-1968
=> Link destination change

pages/common/content/success-messages.js, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/index.jsx, pages/task/read/middleware/update-data.js
* withdrawn drafts are no longer a thing - refactor project landing page to remove this extra complexity
* Added extra state for when task is recalled and editable
=> Fork on recall

pages/common/content/success-messages.js, pages/project/read/views/index.jsx, pages/project/update-licence-holder/content/index.js, pages/project/update-licence-holder/routers/confirm.js, pages/project/update-licence-holder/routers/update.js, pages/project/update-licence-holder/schema/index.js, pages/project/update-licence-holder/views/confirm.jsx, pages/project/update-licence-holder/views/index.jsx, pages/task/read/middleware/update-data.js
Added middlware for updating the licence holder task when editable by applicant
=> Update change licence holder task

pages/project-version/middleware/index.js
The code that iterates over a task's status changes to determine if it is "with ASRU" or not is both broken (it doesn't know about recall) and redundant (tasks come with a `withASRU` property).
This currently means that recalled tasks can't be commented on by external users because the code incorrectly determines them to be with ASRU. By removing the code completely and using the property attacked to the task then the status is correctly determined.
=> Use task's `withASRU` property to determine if a task is with ASRU

package-lock.json, package.json, pages/project-version/docx/index.js, pages/project/update-licence-holder/schema/experience-fields.js
There's a breaking change coming that turns the exported schema into functions. Make sure that the functions are called correctly.
=> Call exported schema functions

pages/task/list/content/fields.js, pages/task/list/router.js
...depending on who is viewing and which tab they are on.
=> Change the updatedAt column name in the tasklist

pages/establishment/update/views/authorisations.jsx
Condition was checking if an array was greater than zero, which makes no sense. Add a missing `.length`.
=> Add `.length` where it was missing

pages/project-version/middleware/index.js
Logic should be performed workflow side, not here
=> Clean out comment filtering code

package-lock.json, package.json, pages/project-version/middleware/index.js, pages/project-version/read/index.js, pages/project-version/read/js/index.js
* added middleware for collecting list of protocols from previous version and granted version
* use middleware in read view
=> Feature - reorder protocols

pages/common/content/success-messages.js, pages/task/content/status.js, pages/task/read/content/confirm.js, pages/task/read/content/pil.js, pages/task/read/content/project.js, pages/task/read/routers/view.js, pages/task/read/views/confirm.jsx, pages/task/read/views/models/project.jsx
Updates to statuses and success messages for endorsement - also filtered end states from activity log if came from endorsedd
=> Updates to content

pages/common/views/pdf/header.jsx, pages/pil/read/content/index.js, pages/pil/read/schema/index.js, pages/pil/read/views/index.jsx
Also adds a "Last amended" field to the PIL digital view (displays ` - ` if not amended).
=> Hide amend date unless greater than issue date

pages/project-version/read/js/index.js
This isn't being set on init as per editing interface
=> Bugfix - include savedConditions on init

pages/user/update-email/content/index.js, pages/user/update-email/routers/confirm.js, pages/user/update-email/schema/index.js
* Better label for the password field
* Early fail on entering current email as new email
* Proper form error if new email is already in use
=> Change email improvements

pages/project/read/content/index.js, pages/project/read/views/index.jsx
Updated copy for users who have permission to view a project but not update
=> Bugfix - internal copy on project landing page

package-lock.json, package.json, pages/project/update-licence-holder/schema/experience-fields.js
Use only the schema subset we need, and don't load what amounts to the entire projects UI to get some field config.
=> Optimise experience fields

pages/common/assets/sass/style.scss, pages/pil/update/content/index.js, pages/pil/update/views/index.jsx, pages/pil/update/views/section-details.jsx
Displays the establishment name the PIL is associated with.
=> Add establishment section to PIL

package-lock.json, package.json, pages/establishment/details/views/index.jsx, pages/establishment/index.js, pages/establishment/pdf/index.jsx
* bumped components with download header change to allow no dl opts
* check user perms before showing pdf link
* add perms to routers
* catch after promise chain in PDF renderer
=> Bugfix - PDF perms

pages/common/assets/sass/style.scss, pages/common/content/index.js, pages/pil/species/content/index.js, pages/pil/species/index.js, pages/pil/species/schema/index.js, pages/pil/species/views/index.jsx, pages/pil/update/content/index.js, pages/pil/update/index.js, pages/pil/update/views/index.jsx, pages/pil/update/views/section-details.jsx
* Added species section to pil
* removed species merging from exemptions/modules
=> Feature - top level species selector for PILs

package-lock.json, package.json, pages/project-version/middleware/index.js
Correctly handle species selector and permissible purposes when showing diff
Waiting for https://github.com/UKHomeOffice/asl-projects/pull/452
=> Bugfix - project version diff

pages/pil/content/index.js, pages/pil/exemptions/routers/exempt.js, pages/pil/helpers/species.js, pages/pil/procedures/index.js, pages/pil/species/index.js, pages/pil/training/content/index.js, pages/pil/training/routers/certificate.js, pages/pil/training/routers/exempt.js, pages/pil/update/content/index.js, pages/pil/update/index.js, pages/pil/update/views/index.jsx
Also fixes a bug when submitting the exemptions form without selecting any modules.
=> Always show declaration on PIL application

pages/pil/dashboard/views/index.jsx, pages/pil/delete/content/index.js, pages/pil/delete/index.js
* Updated delete router to only delete on post /delete
* Added form with window.confirm to draft pils
* added success message
=> Feature - delete PIL

pages/pil/dashboard/views/index.jsx, pages/pil/delete/index.js
* Redirect to profile.read on discard
* Fixed button styling
=> Bugfix - fix redirect on pil discard

pages/pil/species/index.js
As https://github.com/UKHomeOffice/asl-pages/pull/604 except for species as well.
=> Don't assume saved session values exist

pages/profile/invitations/content/index.js, pages/profile/invitations/index.js, pages/profile/invitations/views/index.jsx, pages/profile/list/views/index.jsx, pages/profile/routes.js
* Added resend cancel/delete options to invitations
* Added success notifications
waiting for https://github.com/UKHomeOffice/asl-resolver/pull/118
and
https://github.com/UKHomeOffice/asl-public-api/pull/196
=> Feature - Invitation actions

pages/pil/training/routers/modules.js, pages/pil/training/routers/species.js
Not sure if this is necessarily a session timeout, or someone using browser history/bookmarks.
Either way it needs to not fail.
=> Prevent error if session times out while entering training

lib/validation/index.js, pages/common/routers/form.js, pages/pil/training/content/index.js, pages/pil/training/views/index.jsx, test/unit/routers/form.spec.js
* Update form router to validate relevant option reveals
* Pass errors to connected child component
=> Bugfix - reveal validation

pages/common/routers/form.js, pages/pil/exemptions/content/modules.js, pages/pil/exemptions/routers/modules.js, pages/pil/exemptions/schema/modules.js, pages/pil/exemptions/views/modules.jsx, test/unit/routers/form.spec.js
* Removed custom validator logic
* Removed form overrides
* Added logic to get reveal values from body if applic
=> Bugfix - exemptions reveal fields

pages/common/content/success-messages.js, pages/common/routers/success.js, pages/establishment/update/routers/confirm.js, pages/establishment/update/views/confirm.jsx
* Removed declaration if asru user submitting change to establishment details
* Added licensing officer and inspector specific success messages when submitting an update to establishment details
=> Feature - remove declaration for asru

pages/role/routers/confirm.js, pages/role/views/confirm.jsx
* Remove declaration for role creation and removal if asru
* Updated to use standard form
* removed superfluous params from template
=> Feature - remove asru declaration - roles

pages/establishment/update/routers/confirm.js, pages/place/create/index.js, pages/place/index.js, pages/place/routers/confirm.js, pages/place/update/views/confirm.jsx, pages/role/remove/content/confirm.js, pages/role/routers/confirm.js
* Removed declaration if ASRU for create update and delete
* Fixed copy on delete role confirm page - submit to ASRU -> submit
=> Feature - Remove declarations if ASRU changes SOP

pages/pil/read/content/index.js, pages/pil/read/schema/index.js, pages/pil/read/views/index.jsx
* Added establishmentName prop to schema
* Added formatter to show messgage if undefined
* Added label
needs https://github.com/UKHomeOffice/asl-public-api/pull/199 to stop WIPing
=> Feature - include est name on PIL landing page

pages/pil/read/index.js, pages/pil/read/views/index.jsx
* Removed params from req.user.can call
* Added permissions check for download
* Hide DL link if user cannot DL
needs 
https://github.com/UKHomeOffice/asl-permissions/pull/51
=> Bugfix - pil dl perms

pages/pil/dashboard/index.js
* pil.dashboard had an extra permissions check passing the wrong params, removed
=> Bugfix - removed extra perms check

pages/common/routers/datatable.js
Allows downloading a CSV version of the data in a table by appending a `?csv=1` to the page's query string.
=> Add CSV export functions to datatable router

package-lock.json, package.json, pages/common/routers/datatable.js
This will handle values with commas or newlines in them much better than naive string concatenation.
Also reset page to the first page if downloading the csv or there'll be no data.
=> Use CSV generation lib to generate CSVs

package-lock.json, package.json, pages/project/formatters/index.jsx
Needs https://github.com/UKHomeOffice/asl-components/pull/103 bumping first
=> Hide the countdown unless the licence is active

lib/utils/index.js, pages/pil/dashboard/index.js, pages/pil/dashboard/views/index.jsx, pages/pil/establishment/index.js
Needs https://github.com/UKHomeOffice/asl-public-api/pull/213
=> Allow ASRU to initiate PIL transfers

pages/task/read/views/components/activity-log.jsx
This was already built but must've got lost during a refactoring at some point.
=> Fix broken extended by activity message

pages/common/assets/sass/style.scss, pages/common/content/success-messages.js, pages/task/content/status.js, pages/task/read/content/base.js, pages/task/read/routers/discard.js, pages/task/read/routers/index.js, pages/task/read/routes.js, pages/task/read/views/models/index.jsx, pages/task/schema/view.js
Needs https://github.com/UKHomeOffice/asl-workflow/pull/202
=> Add ability for asru admin to discard tasks with no changes made

pages/task/list/router.js
If a user breaks the URL with a progress param in the query string that does not match one of the allowed states then throw a NotFoundError instead of trying to resolve it and failing.
=> Throw NotFoundError if provided a non-existent progress param

package-lock.json, package.json, pages/establishment/read/views/index.jsx, pages/pil/read/views/index.jsx, pages/project-version/read/views/index.jsx
~Waiting for 
https://github.com/UKHomeOffice/asl-components/pull/106
https://github.com/UKHomeOffice/asl-projects/pull/501~
=> Improved licence / download headers

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/place/content/fields.js, pages/place/formatters/index.jsx, pages/place/index.js, pages/place/routers/update.js, pages/place/schema/index.js, pages/place/update/content/index.js, pages/place/update/views/confirm.jsx, pages/place/update/views/index.jsx, pages/task/read/content/place.js, pages/task/read/routers/read.js, pages/task/read/views/index.jsx, pages/task/read/views/models/index.jsx, pages/task/read/views/models/place.jsx
* Replaced conditional reveal and text with new restrictions field type for place edits
* Replaced Field with EditableField in place task review.
* Added warning if user navigates away from task after changing restrictions and not progressing the task
=> Feature - restrictions improvements

pages/project-version/routes.js, pages/project-version/update/index.js, pages/project-version/update/js/index.js, pages/project-version/update/router.js, pages/project-version/update/submit/content/index.js, pages/project-version/update/submit/index.js, pages/project-version/update/submit/schema/index.js, pages/project-version/update/submit/views/index.jsx, pages/project-version/update/success/index.js, pages/project-version/update/success/views/index.jsx, pages/project-version/update/views/index.jsx, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/index.jsx, pages/task/read/views/models/project.jsx
* Moved project version submission and update code from asl
* Added extra conditions to project landing page - messaging for asru users not able to edit as establishment have started an amend, and vise versa
=> Feature - Licensing PPL updates

package-lock.json, package.json, pages/establishment/licence-fees/views/index.jsx, pages/pil/establishment/views/index.jsx, pages/task/read/views/models/index.jsx
To ensure working-ness in browsers that don't support the details element natively.
=> Replace details html with Details component

pages/common/content/index.js
Fix spelling mistake in `aplicant` and make consistent with expired and revoked banner
=> Fix content in superseded banner

pages/establishment/licence-fees/content/index.js, pages/establishment/licence-fees/details/content/index.js, pages/establishment/licence-fees/details/index.js, pages/establishment/licence-fees/details/read/index.js, pages/establishment/licence-fees/details/read/views/index.jsx, pages/establishment/licence-fees/details/routes.js, pages/establishment/licence-fees/details/schema/index.js, pages/establishment/licence-fees/details/update/content/index.js, pages/establishment/licence-fees/details/update/index.js, pages/establishment/licence-fees/details/update/views/index.jsx, pages/establishment/licence-fees/routes.js, pages/establishment/licence-fees/views/index.jsx
* Added billing details tab to licence-fees page
* Added update billing details form
=> Feature - update billing

pages/common/assets/sass/style.scss, pages/common/content/success-messages.js, pages/establishment/dashboard/views/index.jsx, pages/establishment/index.js, pages/establishment/read/content/index.js, pages/establishment/read/views/index.jsx, pages/pil/read/views/index.jsx
Waiting on https://github.com/UKHomeOffice/asl-internal-api/pull/54
=> Revoke PEL

pages/common/content/success-messages.js, pages/common/views/success.jsx, pages/user/update/content/index.js, pages/user/update/index.js, pages/user/update/views/success.jsx
* Added success page for non-autoresolving profile updates
* Added content for with-licensing profile updates
=> Bugfix - success page for profile updates

pages/profile/content/fields.js, pages/profile/content/index.js, pages/profile/invite/views/index.jsx, pages/profile/permission/content/index.js, pages/profile/permission/views/index.jsx
* updated content on permissions selection page, profile page and invitation page
* Used <Form> components as layouts dont work with detachFields
=> Content - updated permission content

package-lock.json, package.json, pages/project-version/downloads/views/index.jsx
=> Download page should be relevant to version not project

pages/project-version/middleware/index.js
Making changes to content was causing conditions to show as changed. Remove conditions completely when comparing a draft version, and when comparing submitted versions ensure that the conditions are sorted before comparison to avoid false positives when ordering changes.
=> Ignore conditions in comparison of draft PPLs

pages/project/content/index.js, pages/project/read/views/index.jsx
~Waiting for confirmation of content, and a negative state~
=> Add RA date to project landing page

pages/common/assets/sass/style.scss, pages/establishment/licence-fees/overview/views/summary-table.jsx, pages/establishment/licence-fees/views/index.jsx, pages/pil/read/views/index.jsx, pages/project/list/views/index.jsx, pages/project/read/views/index.jsx, pages/task/read/views/components/activity-log.jsx
* control panel doesn't need to be a p
* fixed various content mismatch errors
* dont put a form in a p
=> Bugfix - content mismatches

package-lock.json, package.json, pages/common/views/pdf/standard-conditions.jsx, pages/establishment/pdf/views/establishment.jsx, pages/pil/pdf/views/pil.jsx, pages/place/list/views/row.jsx, pages/task/read/views/models/project.jsx
WIP until https://github.com/UKHomeOffice/asl-components/pull/116
=> replaced react markdown with custom markdown component to strip links

pages/project/delete/content/index.js, pages/project/delete/index.js, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/index.jsx
~Waiting on https://github.com/UKHomeOffice/asl-internal-api/pull/57~
=> Add discard project stub function

pages/project-version/components/project-status-banner.jsx
When looking for the end date of a project version's validity period, don't look only for the next version, but specifically for the next granted version.
=> Find next granted version

pages/task/read/routers/read.js
If update action then get project, if not get version
=> Bugfix - update licence holder doesn't have a version

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/pil/dashboard/views/index.jsx
~Waiting on https://github.com/UKHomeOffice/asl-components/pull/121~
=> Remove redundant styling for definition lists

package-lock.json, package.json, pages/establishment/read/content/index.js, pages/pil/read/content/index.js
~waiting on https://github.com/UKHomeOffice/asl-projects/pull/534~
=> Update broken conditions links

pages/common/content/success-messages.js, pages/project-version/lib/extract-comments.js, pages/task/read/routers/read.js, pages/task/read/views/components/activity-log.jsx
* Added missing referred to inspector success messages
* Removed activity log filtering logic - this is now handled in workflow
* Updated activity log to show status and action from task
=> Feature - PPL transfer content

pages/project/content/index.js, pages/project/formatters/index.jsx, pages/project/list/index.js, pages/project/list/views/index.jsx, pages/project/schema/index.js
* Updated columns to active, inactive and drafts
* Added status col to inactive licences (expired, revoked and transferred)
* removed redundant sequelize filter
=> Feature - PPL list updates

pages/task/read/views/components/activity-log.jsx
* this was lost in a previous commit - action should be per type - revoke etc
=> Bugfix - allow per type actions

pages/project-version/read/index.js, pages/project-version/read/js/index.js, pages/task/read/content/project.js, pages/task/read/routers/read.js, pages/task/read/views/models/project.jsx
* added diff to task page
* skip est api call if ppl xfer - we cannot reeliably know which establishment the task is pointing at, and if the user has permission to view.
=> Feature - PPL xfter est diff

pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/index.jsx
* Added alternate description if user can transfer licence
=> Feature - ppl xfer text

pages/profile/convert-legacy-project/index.js, pages/profile/read/index.js
Enable the feature without the env var being required.
=> Remove the feature flag on ppl conversion

pages/common/assets/sass/style.scss, pages/common/content/index.js, pages/profile/index.js, pages/profile/read/content/index.js, pages/role/apply/content/confirm.js, pages/role/apply/content/index.js, pages/role/apply/index.js, pages/role/apply/views/index.jsx, pages/role/component/open-tasks.jsx, pages/role/remove/content/confirm.js, pages/role/remove/content/index.js, pages/role/remove/index.js, pages/role/remove/views/index.jsx
~Waiting on https://github.com/UKHomeOffice/asl-public-api/pull/236~
=> Prevent multiple tasks being raised for the same person/role/establishment

pages/common/content/index.js, pages/establishment/dashboard/content/index.js, pages/establishment/dashboard/views/index.jsx, pages/index.js, pages/pil/list/content/index.js, pages/pil/list/index.js, pages/pil/list/schema/index.js, pages/pil/list/views/index.jsx
* added PIL list page, sort by review date by default
=> Feature - PIL list

pages/common/content/index.js, pages/project/add-user/content/index.js, pages/project/add-user/index.js, pages/project/add-user/schema/index.js, pages/project/add-user/views/index.jsx, pages/project/components/collaborators.jsx, pages/project/content/index.js, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/components/manage-access.jsx, pages/project/read/views/components/section.jsx, pages/project/read/views/index.jsx, pages/project/remove-user/content/index.js, pages/project/remove-user/index.js, pages/project/routes.js
* added collaborators table
* added add users interface
* added router for removing users
=> Feature - manage project collaborators

pages/common/assets/sass/pdf/index.scss, pages/project-version/pdf/views/nts/v0.jsx, pages/project-version/pdf/views/nts/v1.jsx
Might wanna tick the "hide whitespace changes" option on this one.
=> Avoid page breaks between questions and answers in the NTS PDF

package-lock.json, package.json, pages/project-version/docx/index.js, pages/project-version/downloads/content/index.js
waiting on https://github.com/UKHomeOffice/asl-projects/pull/553
=> display primary establishment in docx

pages/common/assets/sass/style.scss, pages/task/list/content/index.js, pages/task/list/views/table.jsx, pages/task/read/content/project.js, pages/task/read/views/models/project.jsx
* Added formatters for continuation in task lists
* Added continuation info to project task pages if present
=> Feature - continuation

pages/project/read/views/index.jsx
project.draft is not set once version is submitted
=> Bugfix: show correct amendment in progress notice to external users once draft is submitted by ASRU

pages/task/list/views/table.jsx
* If expiry is missing dont try and render it
=> Bugfix - dont try and render invalid date

pages/task/list/views/table.jsx
There's a worry that these might be slightly controversial, and we will want to hold off deploying them. Prepping this in case that is the decision.
=> Revert task list changes around continuation

pages/project-version/middleware/index.js
These are being loaded on every request, when in reality they change very rarely - and when they do change the ID also changes.
This means we can vastly improve performance by not re-requesting them on every request, but storing them in the user's session.
=> Use a session cache when loading granted and previous PPL versions

pages/role/apply/content/index.js, pages/role/apply/index.js, pages/role/apply/views/index.jsx, pages/role/content/named-roles.js
* Reordered roles
* Use contextual label for comments box
* Added profile name to add roles page
=> Content - update content for named roles

pages/task/list/content/index.js, pages/task/list/views/table.jsx, pages/task/read/content/project.js, pages/task/read/views/models/project.jsx
* Replaced deadline component with text label
* Playback original contnuation RTE on task page if present
=> Continuation changes

pages/common/assets/sass/style.scss, pages/task/list/views/table.jsx
* Added licence number for PIL and PPL when present
* reduce font size
=> Feature - licence numbers on task list

pages/pil/read/index.js, pages/pil/read/views/index.jsx
These are currently showing on revoked PILs
=> Only show review due banner on active PILs

pages/common/assets/sass/style.scss, pages/common/formatters/index.jsx, pages/place/schema/index.js
* Added hint text for STH
* Updated label from code helper to accept objects
=> Feature - hint text for STH holding code

pages/common/assets/sass/pdf/index.scss, pages/project-version/pdf/views/nts/v0.jsx
* Replace repeated reduction with refinement
* Include headers in wrappers
* Remove page break rule
=> Bugfix - repeated reduction in legacy NTS

package-lock.json, package.json, pages/common/assets/sass/pdf/index.scss, pages/common/helpers/pdf.js, pages/project-version/downloads/content/index.js, pages/project-version/downloads/views/index.jsx, pages/project-version/pdf/index.jsx, pages/project-version/pdf/views/protocols.jsx, pages/project-version/routes.js
* Added link to downloads page
* Added route to pdf router
* Allowed orientation to be configurable
* Added table for protocols and adverse effects
* Updated styles for protocol summary table
=> Feature - PDF protocols table

pages/place/content/index.js, pages/place/routers/confirm.js
Needs
https://github.com/UKHomeOffice/asl-workflow/pull/267
https://github.com/UKHomeOffice/asl-public-api/pull/249
=> Display toaster success for role changes

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/common/helpers/index.js, pages/common/middleware/index.js, pages/establishment/components/named-people.jsx, pages/establishment/dashboard/views/index.jsx, pages/place/content/fields.js, pages/place/formatters/index.jsx, pages/place/index.js, pages/place/list/content/index.js, pages/place/list/schema/index.js, pages/place/list/views/index.jsx, pages/place/routers/confirm.js, pages/place/routers/update.js, pages/place/schema/index.js, pages/task/read/routers/read.js, pages/task/read/views/models/place.jsx
~Needs 
https://github.com/UKHomeOffice/asl-components/pull/130
https://github.com/UKHomeOffice/asl-public-api/pull/248~
=> Assign multiple NACWOs

pages/establishment/update/views/authorisations.jsx, pages/task/read/content/base.js, pages/task/read/content/establishment.js, pages/task/read/content/place.js, pages/task/read/content/project.js, pages/task/read/routers/read.js, pages/task/read/views/models/establishment.jsx, pages/task/read/views/models/pil.jsx, pages/task/read/views/models/place.jsx, pages/task/read/views/models/profile.jsx, pages/task/read/views/models/project.jsx
* Updated diff component labels when task completed to previous and changed to
* updated task read router to use modelData rather than looking up model
* Updated diff text and custom diff components to show correct labels when task is complete
=> Bugfix - completed task diffs

pages/common/views/success.jsx
Specifically, when submitting a PPL the profile is not available so is currently throwing an error.
=> Profile is not always set, so check before reading email property

pages/common/views/success.jsx
To help better identify complete transactions in functional testing.
=> Add success classname to success panel

pages/task/read/views/models/establishment.jsx
Use previous conditions from activity log, not est model
=> Bugfix - establishment update conditions

pages/common/assets/sass/style.scss, pages/establishment/dashboard/views/index.jsx, pages/global-profile/components/asru-roles.jsx, pages/global-profile/content/index.js, pages/global-profile/index.js, pages/global-profile/views/index.jsx, pages/index.js, pages/profile/read/views/profile.jsx, pages/task/read/views/components/activity-log.jsx
* Added global profile page from internal ui
* Stripped out asru actions
* allow own profile and asru profiles
* show edit links if own profile
* show related tasks if not asru user
=> Feature - global profile

package-lock.json, package.json, pages/project-version/lib/extract-comments.js
~waiting on https://github.com/UKHomeOffice/asl-projects/pull/578~
=> Sort comments newest first

package-lock.json, package.json, pages/project-version/update/router.js
Checks the projects version from the request header to make sure it is compatible with the version being run on the server.
If it is not compatible then don't allow the update to be saved and return an `UPDATE_REQUIRED` message.
~WIP pending https://github.com/UKHomeOffice/asl-projects/pull/583~
=> Reject PPL patches if not sent by a compatible projects version

pages/task/read/views/models/pil.jsx
* Show training from task if present
* Dont fallback to current training
=> Feature - PIL training in tasks

package-lock.json, package.json, pages/common/assets/sass/pdf/_base.scss, pages/common/assets/sass/pdf/index.scss, pages/project-version/downloads/content/index.js, pages/project-version/downloads/views/index.jsx, pages/project-version/pdf/index.jsx, pages/project-version/pdf/views/protocols.jsx
* Added link to downloads page
* Added fullApplication option to PDF
* Tweaked pdf margins
* hella loadsa style changes
=> Feature - pdf ppl application

pages/project-version/update/submit/index.js, pages/project-version/update/submit/schema/index.js
* only show the inspector declaration if the project has an existing task
=> Feature - remove inspector declaration for first submission

pages/task/read/views/models/project.jsx
removed the pel holder name and endorsement date playback from a ppl task review page
=> Feature - remove PEL holder endorsement questions

package-lock.json, package.json, pages/project-version/update/submit/content/index.js, pages/project-version/update/submit/index.js, pages/project-version/update/submit/views/index.jsx
If admin user submits a ppl then show a declaration, and remove warning text about requiring endorsement
=> Feature - PPL submit declaration

package-lock.json, package.json, pages/project/add-user/schema/index.js, pages/project/update-licence-holder/schema/index.js
* Updated components with autocomplete
* Implemented on project change licence holder and invite collab
=> Feature - autocomplete

package-lock.json, package.json, pages/project/update-licence-holder/routers/update.js
* this prevents the autocomplete being prefilled with the current licence holder. Values stored in session are preserved and show as normal
* Bumped components with bugfix for on Blur
=> Clear licence holder id from model

pages/profile/read/content/index.js, pages/profile/read/index.js, pages/profile/read/views/leave-establishment.jsx, pages/profile/read/views/profile.jsx, pages/profile/remove/index.js, pages/profile/routes.js
* added leave establishment component
* show leave est if own profile
=> Feature - leave establishment

package-lock.json, package.json, pages/profile/read/index.js, pages/profile/read/views/leave-establishment.jsx
* Bumped components with getUrl function
* Use getUrl in remove profile component
=> Feature - use getUrl in remove profile

pages/common/content/index.js, pages/user/menu/views/index.jsx, pages/user/routes.js, pages/user/update-password/content/index.js, pages/user/update-password/index.js, pages/user/update-password/schema/index.js, pages/user/update-password/views/index.jsx
~needs https://github.com/UKHomeOffice/asl-public-api/pull/260~
=> Allow the user to change their keycloak password

pages/user/update-email/content/index.js, pages/user/update-email/views/index.jsx
* This was being inherited from elsewhere, removed hint.
* Added guidance content to top of page
=> Bugfix - email hint

package-lock.json, package.json, pages/project-version/read/js/index.js, pages/project-version/update/js/index.js
* Pass version.raCompulsory to projects in read and edit views
=> Feature - RA as data

pages/task/read/content/role.js, pages/task/read/routers/read.js, pages/task/read/views/models/role.jsx
~needs https://github.com/UKHomeOffice/asl-workflow/pull/289~
=> Playback remaining roles at an establishment on role delete tasks

pages/project-version/pdf/index.jsx, pages/project-version/pdf/views/nts/components/retrospective-assessment.jsx, pages/project-version/pdf/views/nts/v0.jsx, pages/project-version/pdf/views/nts/v1.jsx
* Pass the raCompulsory prop to pdf init
* Replaced repeated RA component with one from projects which handles the compulsory state.
=> Bugfix - RA in pdfs

package-lock.json, package.json, pages/project-version/pdf/views/nts/v1.jsx
The options for PP are not where they used to be, so import directly.
Apply an override for PP in training PPLs.
=> Fix permissible purposes in NTS download

pages/common/assets/sass/style.scss, pages/project/content/index.js, pages/project/formatters/index.jsx, pages/project/list/views/index.jsx, pages/project/schema/index.js
* Show status labels on each tab in ppl list
* Show RA Required label if applic
=> Feature - Added RA required labels to PPL list

pages/project-version/pdf/views/nts/v1.jsx
Removes the questions which are not asked for T&E projects and adds the new questions from the NTS sections.
=> Fix NTS export for T&E PPLs

pages/pil/dashboard/index.js, pages/pil/dashboard/views/index.jsx, pages/pil/training/content/index.js, pages/pil/training/index.js
This ensures validation errors are scoped correctly
=> Bugfix - use unique id for training section of pil

package-lock.json, package.json, pages/project-version/update/submit/content/index.js, pages/project-version/update/submit/index.js, pages/project-version/update/submit/schema/index.js, pages/project-version/update/submit/views/index.jsx, pages/task/read/content/confirm.js, pages/task/read/routers/confirm.js, pages/task/read/views/models/project.jsx, pages/task/schema/confirm.js
waiting on 
~https://github.com/UKHomeOffice/asl-public-api/pull/272~
~https://github.com/UKHomeOffice/asl-workflow/pull/301~
=> Move awerb question to admin ppl endorsement

pages/global-profile/views/index.jsx
* Updated to use TrainingSummary
* Removed training link - this is only currently on establishment scoped profiles
=> Bugfix - Fixed training for global profile

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/establishment/licence-fees/content/index.js, pages/establishment/licence-fees/index.js, pages/establishment/licence-fees/views/index.jsx
* bumped react-components so classNames can be added to select groups
* added select with available years
* redirect on select change
=> Feature - billing year ui

package-lock.json, package.json, pages/project/update-licence-holder/routers/confirm.js, pages/project/update-licence-holder/routers/update.js, pages/project/update-licence-holder/schema/experience-fields.js, pages/task/read/routers/read.js, pages/task/read/views/models/project.jsx
Get the active project version and use to evaluate which of the conditional fields in the experience section of the PPL scehma should be used in the change PPL holder journey.
=> Evaluate conditional fields in change PPL holder form

pages/pil/review/views/success.jsx
we are recycling a breadcrumb here which has changed location
=> Bugfix - success content for pil review

pages/task/read/content/project.js, pages/task/read/views/components/activity-log.jsx
Adds the date to the "view this version link"
Only displays the version link for endorsement actions or resubmissions by an admin.
=> Activity log improvements

pages/common/assets/sass/style.scss, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/ppl-declarations.jsx, pages/task/read/views/models/project.jsx
~Will need rebasing once https://github.com/UKHomeOffice/asl-pages/pull/916 is merged, this is a continuation of that work.~
=> Activity log awerb/authority/ready question playback

pages/place/create/content/confirm.js, pages/place/create/content/index.js, pages/place/delete/content/confirm.js, pages/place/delete/content/index.js, pages/place/delete/index.js, pages/place/routers/confirm.js, pages/place/update/content/confirm.js, pages/place/update/content/index.js
`settings.page` was undefined - just pass the actual route string instead.
=> the edit link on the delete place confirm page was broken

package-lock.json, package.json, pages/project-version/middleware/index.js
Return the correct values when looking for values for the `reduction-quantities` field.
~Needs https://github.com/UKHomeOffice/asl-projects/pull/628 for the helper function to exist~
=> Detect changes to reduction-quantities field

package-lock.json, package.json, pages/establishment/index.js, pages/establishment/licence-fees/content/index.js, pages/establishment/licence-fees/index.js, pages/establishment/licence-fees/views/index.jsx, pages/global-profile/index.js, pages/pil/read/content/index.js, pages/pil/unscoped/list/index.js, pages/place/content/index.js, pages/place/index.js, pages/profile/index.js, pages/profile/list/index.js, pages/project/index.js, pages/project/list/content/index.js, pages/project/list/index.js, pages/role/apply/index.js, pages/role/remove/index.js, pages/task/list/content/index.js, pages/training/index.js, pages/user/menu/content/index.js, pages/user/update-email/content/index.js, pages/user/update-password/content/index.js, pages/user/update/content/index.js
Prefix the site title with specific page titles in assorted contexts
=> Add page titles

pages/task/read/views/models/pil.jsx
* Cat e pils wont be set for existing tasks
=> Bugfix - dont assume cat es set

pages/project-version/update/index.js
Not really sure why this is happening, but it is, and it's causing errors.
=> Handle the case where a user ends up on GET /update-training in a PPL

package-lock.json, package.json, pages/common/assets/sass/_ho-frontend-toolkit.scss
Uses https://design-system.service.gov.uk/components/skip-link/
~waiting on https://github.com/UKHomeOffice/asl-service/pull/209/files~
=> Include a hidden skip to main content link in the header of every page

pages/pil/unscoped/courses/participants/read/views/training-pil.jsx
* Updated schema of participant view to use correct accessor
=> Bugfix - licence number missing in task cat e view

pages/task/read/routers/read.js
We were showing the message to non-NTCOs
=> Only warn NTCOs about self endorsement

pages/establishment/licence-fees/personal/index.js, pages/establishment/licence-fees/personal/schema/index.js, pages/establishment/licence-fees/personal/views/row.jsx
Change the `pilId` param in most places where we deal with fee waivers to `profileId`
=> Change PIL fee waivers to be based on profiles not PIL records

pages/common/routers/form.js, pages/establishment/formatters/index.jsx, pages/establishment/read/content/index.js, pages/establishment/read/views/index.jsx, pages/establishment/update/content/fields.js, pages/establishment/update/routers/confirm.js, pages/establishment/update/schema/index.js, pages/establishment/update/views/confirm.jsx, pages/task/read/content/establishment.js, pages/task/read/views/models/establishment.jsx
* updated schema to include isTrainingEst
* updated task diff and confirm diff
* updated form router to format reveals as well as top level fields
=> Feature - set isTrainingEst

package-lock.json, package.json, pages/establishment/read/content/index.js, pages/establishment/read/views/index.jsx, pages/profile/list/views/index.jsx
~Needs https://github.com/UKHomeOffice/asl-components/pull/169~
=> Add a filter to the profiles list that shows all named people

package-lock.json, package.json, pages/training/certificate/index.js, pages/training/certificate/views/index.jsx, pages/training/dashboard/views/index.jsx, pages/training/index.js, pages/training/middleware/index.js, pages/training/modules/index.js, pages/training/modules/views/index.jsx, pages/training/remove/index.js, pages/training/routes.js, pages/training/type/index.js, pages/training/type/views/index.jsx, pages/user/menu/content/index.js, pages/user/menu/index.js, pages/user/menu/views/index.jsx
* updated training section to use basePage for links
* updated api routes to use /me is estId not set
=> Feature - training in account

pages/profile/read/content/index.js, pages/profile/read/views/profile.jsx, pages/role/apply/index.js
If a user has, or is adding, an NVS role then display the RCVS numebr from their profile in the relevant places.
=> Populate RCVS number on NVS roles

package-lock.json, package.json, pages/place/list/schema/index.js
Also bump components for clear filters fix.
=> Disable sorting on suitability/holding

pages/pil/unscoped/courses/create/index.js, pages/pil/unscoped/courses/list/content/index.js, pages/pil/unscoped/courses/list/index.js, pages/pil/unscoped/courses/read/index.js
These were showing `undefined` before
=> Add page titles for training course section

pages/project-version/update/submit/index.js, pages/task/read/views/components/activity-log.jsx
If a PPL is being endorsed, store the declaration in the metadata for later playback in the activity log.
=> Play back declaration text if present in the activity payload

pages/project-version/nts/views/index.jsx, pages/project-version/pdf/index.jsx
raCompulsory is an actual property of the version and not a prop of the version data.
=> Copy raCompulsory to the version data so it can be used by RA component

package-lock.json, package.json, pages/common/content/index.js, pages/project-version/components/project-status-banner.jsx, pages/project-version/middleware/index.js, pages/project-version/read/index.js, pages/project/content/index.js, pages/project/formatters/index.jsx, pages/project/list/views/index.jsx, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/components/manage-access.jsx, pages/project/read/views/index.jsx, pages/project/routes.js, pages/task/read/content/project.js, pages/task/read/views/models/project.jsx
* Bumped projects with AA feature
* Added additional availbility section to task page
* Updated status banners to take AA into account
* updated project page to hide certain sections if AA
=> Feature - additional availability

pages/project-version/update/js/index.js
* Use licence holder establishemnts if editing as an asru user
=> Feature - asru AA

pages/project-version/nts/views/components/fate-of-animals.jsx
This content has moved into NTS section
=> Get `fate-of-animals` from correct location

pages/task/read/content/base.js, pages/task/read/routers/confirm.js
* Added alternate labels for when comment required
=> Content - updated comment required label

pages/pil/training/index.js, pages/project-version/update/index.js, pages/training/certificate/content/index.js, pages/training/dashboard/content/index.js, pages/training/dashboard/views/index.jsx, pages/training/modules/index.js, pages/training/type/content/index.js
* Updated isExemption to take model into account
* Content changes for hint text
=> Feature - training changes

package-lock.json, package.json, pages/pil/unscoped/list/views/index.jsx, pages/place/list/views/index.jsx, pages/profile/list/views/index.jsx, pages/project/list/views/index.jsx, pages/task/list/views/tasklist.jsx
~Waiting on https://github.com/UKHomeOffice/asl-components/pull/182~
=> Pass result type to the FilterSummary for custom label

pages/task/read/views/models/place.jsx
Hide any diffs of named people assigned to places as they do not need to concern ASRU.
=> Changes to assigned named people do not need to be reviewed

pages/common/assets/sass/style.scss, pages/project/formatters/index.jsx, pages/task/read/views/components/establishment-links.jsx, pages/task/read/views/models/project.jsx
* updated proj list formatter to show legacy stup beneath title
* show if held elsewhere
* show AA ests
=> Feature - show AA in project list

pages/common/routers/datatable.js, pages/project/list/index.js, pages/project/list/views/index.jsx, pages/project/schema/index.js
* added download csv link to projects list
* allow csv headers to be configuable
* added schema for project list csv
=> Feature - project csv

pages/profile/read/content/index.js, pages/profile/read/views/profile.jsx
The please add DOB wording was displaying for both the message and link text.
=> Remove duplicate wording about adding dob

pages/profile/read/views/profile.jsx
This ensures the ordering is consistent and not dependent on database insertion ordering.
=> Sort AA establishments when rendering projects on profile pages

package-lock.json, package.json, pages/place/list/content/index.js, pages/place/list/schema/index.js, pages/place/list/views/index.jsx
~waiting on https://github.com/UKHomeOffice/asl-components/pull/187~
=> Add a link to download the csv of all approved areas at est

pages/project/read/views/index.jsx
* Fix condition, show banner if raDate and not grantedRa
=> Bugfix - dont show ra banner on non ra

pages/success/index.js
* projects used to be cause by default, not anymore since a projects case was added
=> Bugfix - how to even switch

pages/retrospective-assessment/update/submit/index.js, pages/retrospective-assessment/update/submit/schema/index.js, pages/retrospective-assessment/update/submit/views/index.jsx, pages/task/read/ra-awerb/index.js
* If an RA is reendorsed, awerb should be confirmed, and declaration re-shown/accepted
=> Bugfix - require re-awerbing on reendorse

pages/project-version/nts/index.js, pages/project-version/nts/views/components/field.jsx, pages/project-version/nts/views/components/ra-summary.jsx
* Get granted RA version, this isnt included by default
* Add field type for radio
=> Bugfix - RA values in NTS

pages/common/routers/datatable.js, pages/pil/unscoped/list/schema/index.js, pages/pil/unscoped/list/views/index.jsx
* Added pils CSV link to pils list
* Updated schema to format dates etc for csv
=> Feature - pils CSV

pages/common/assets/sass/style.scss, pages/common/content/index.js, pages/user/email-preferences/content/index.js, pages/user/email-preferences/index.js, pages/user/email-preferences/schema/index.js, pages/user/email-preferences/views/index.jsx, pages/user/menu/content/index.js, pages/user/menu/views/index.jsx, pages/user/routes.js
needs 
* https://github.com/UKHomeOffice/asl-public-api/pull/311
=> Allow users to update their email alert and newsletter preferences

pages/profile/permission/content/index.js, pages/profile/permission/index.js, pages/profile/permission/views/index.jsx
* Updated label to explain the reason(s) the user cannot be removed
=> Feature - update remove perms label

package-lock.json, package.json, pages/common/assets/sass/pdf/_base.scss, pages/common/assets/sass/pdf/index.scss
~needs https://github.com/UKHomeOffice/asl-projects/pull/686~
=> Display hint text on application pdf

pages/project-version/nts/views/components/purpose.jsx
* key is pupose for legacy licences
=> Bugfix - legacy permissible purpose NTS

pages/establishment/dashboard/content/index.js, pages/establishment/dashboard/views/index.jsx
=> Feature - CJSM email

pages/project/read/content/index.js, pages/project/read/views/components/additional-availability-warning.jsx, pages/project/read/views/index.jsx
* Added warning to project landing page if looking at AA.
=> Feature - AA warning

pages/project-version/middleware/index.js
The normaliser that strips invisible whitespace out of RTE values will trigger a large number of false positives when comparing values. If an RTE value has been flagged as changed then double check the values with invisible whitespace removed before showing a changed flag.
=> Check for whitespace only changes when comparing RTE values

package-lock.json, package.json, pages/project-version/update/submit/schema/index.js
This ensures a new reference is created each time that `getSchema` is called and so the schema cannot be polluted between requests.
=> Define `readyQuestion` inside `getSchema` function

pages/common/routers/form.js, pages/common/routers/index.js, pages/common/routers/multi-step.js, pages/rops/update/config.js, pages/rops/update/index.js, pages/rops/update/views/components/confirm.jsx
* Abstracted stepping logic from rops to own router
* Added middleware to redirect to last valid step if try to access a step out of turn
=> Feature - multi step router

pages/rops/procedures/content/index.js, pages/rops/update/content/index.js
Use `setup` for a noun and `set up` for a verb.
=> Fix more set up/setup

pages/rops/update/index.js, pages/rops/update/views/components/confirm.jsx
* Config page was missing nhp qs, include if applic
* Removed repetition for rendering options
=> Bugfix - include nhps

pages/establishment/update/views/authorisations.jsx
related ticket https://collaboration.homeoffice.gov.uk/jira/browse/ASL-3416
=> Fix error being thrown if authorisations prop was missing

package-lock.json, package.json, pages/common/content/index.js, pages/establishment/dashboard/content/index.js, pages/establishment/dashboard/views/index.jsx, pages/establishment/rops/index.js, pages/establishment/rops/overview/content/index.js, pages/establishment/rops/overview/index.js, pages/establishment/rops/overview/schema/index.js, pages/establishment/rops/overview/views/index.jsx, pages/establishment/rops/routes.js, pages/establishment/routes.js
~needs https://github.com/UKHomeOffice/asl-public-api/pull/318~
=> View all rops due at an establishment for a specific year

pages/rops/index.js, pages/rops/nil-return/views/index.jsx, pages/rops/procedures/content/index.js, pages/rops/procedures/list/views/index.jsx, pages/rops/routes.js, pages/rops/submit/content/confirm.js, pages/rops/submit/content/index.js, pages/rops/submit/index.js, pages/rops/submit/routers/confirm.js, pages/rops/submit/schema/confirm.js, pages/rops/submit/views/confirm.jsx, pages/rops/submit/views/index.jsx, pages/rops/submit/views/success.jsx, pages/success/index.js, pages/task/content/tasks.js, pages/task/list/formatters/index.jsx, pages/task/read/content/index.js, pages/task/read/content/rop.js, pages/task/read/routers/read.js, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/task-status.jsx, pages/task/read/views/models/index.jsx, pages/task/read/views/models/rop.jsx
* Added submit journey
* Updated nil return to use new submit journey
* Added task for submit
=> Feature - submit a ROP

pages/rops/update/views/components/confirm.jsx
=> Bugfix - rop places of birth

pages/rops/procedures/content/index.js, pages/rops/procedures/index.js, pages/rops/procedures/list/views/index.jsx
* added unsubmit rop option if rop is submitted
=> Feature - unsubmit rop

package-lock.json, package.json, pages/project-version/nts/views/components/field.jsx, pages/project-version/nts/views/components/retrospective-decision.jsx, pages/project-version/nts/views/components/retrospective-placeholder.jsx, pages/project-version/nts/views/index.jsx
~waiting on https://github.com/UKHomeOffice/asl-projects/pull/716~
=> Display reasons for RA in NTS when required

pages/user/notifications/index.js, pages/user/notifications/list/content/index.js, pages/user/notifications/list/index.js, pages/user/notifications/list/schema/index.js, pages/user/notifications/list/views/index.jsx, pages/user/notifications/read/content/index.js, pages/user/notifications/read/index.js, pages/user/notifications/read/views/index.jsx, pages/user/notifications/routes.js, pages/user/routes.js
* Added simple notifications datatable for list
* Added simple read view to render markdown
=> Feature - notifications list

pages/project/read/views/components/rops.jsx
* replaced hard coded deadlines with property on model
=> Feature - rops deadline

pages/rops/procedures/index.js, pages/rops/update/views/components/confirm.jsx
* Dont try and render irrelevant questions on procs page for submitted nil return
* Redirect to nil-return if unsubmitted nil-return
=> Bugfix - nil return

pages/project-version/middleware/index.js, pages/project-version/nts/index.js, pages/project-version/nts/views/components/retrospective-decision.jsx, pages/project-version/nts/views/index.jsx, pages/project-version/pdf/index.jsx
use same middleware for digital and pdf views
=> Move ra reasons to project level

pages/common/assets/sass/style.scss, pages/task/content/status.js, pages/task/list/content/fields.js, pages/task/list/formatters/index.jsx, pages/task/list/router.js, pages/task/list/schema/index.js, pages/task/read/content/base.js, pages/task/read/index.js, pages/task/read/routers/assign.js, pages/task/read/routers/read.js, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/asru-assignment.jsx, pages/task/read/views/components/task-status.jsx, pages/task/read/views/models/index.jsx, pages/task/schema/assign.js
* Added assign task interface to task read if ASRU
* Added assignedTo to task list
* Added assign to activity log
=> Feature - assign task

pages/profile/read/content/index.js, pages/profile/read/index.js, pages/profile/read/views/index.jsx, pages/profile/read/views/profile.jsx
Includes a rearrange of the content to use tabs for the project lists.
Review might benefit from hiding whitespace.
=> Show inactive ppls on profile

pages/common/routers/related-tasks.js
Task assignment should only be visible to ASRU users.
=> Remove assigned to column from related task lists for external users

package-lock.json, package.json, pages/project-version/read/index.js, pages/project-version/read/js/index.js, pages/project-version/read/views/index.jsx
* Provide task url and is actionable to project read only view
* Remove next steps button from parent project view, this now lives in projects
~* WIP until corresponding projects change bumped~
=> projects section nav

pages/common/assets/sass/style.scss, pages/project/content/index.js, pages/project/formatters/index.jsx, pages/project/list/views/index.jsx, pages/project/schema/index.js
~waiting on https://github.com/UKHomeOffice/asl-public-api/pull/336~
=> Add RA column to project list with filters for RA status

package-lock.json, package.json, pages/place/list/index.js, pages/place/routers/confirm.js, pages/place/routers/update.js, pages/place/schema/index.js
* Updated site and area to use autocomplete fields
* Added router to get autocomplete values
=> Feature - places autocomplete

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/global-profile/views/index.jsx
~waiting on https://github.com/UKHomeOffice/asl-components/pull/206~
=> Add establishment status to panel title when not active

pages/project/read/content/index.js, pages/project/read/views/components/rops.jsx
* rop not needed if expired or revoked before 1st Jan 2021, added message
=> Bugfix - rop not needed

pages/rops/procedures/create/content/index.js, pages/rops/procedures/create/index.js, pages/rops/procedures/update/content/index.js, pages/rops/procedures/update/index.js
* added messages for add (1 - 5 rows), edit and delete
=> Feature - toaster messages for procs

pages/rops/components/header.jsx, pages/rops/nil-return/content/index.js, pages/rops/nil-return/views/index.jsx, pages/rops/procedures/list/views/index.jsx
* abstracted and reused header for rop on nil return page
=> Feature - nil rop return header

pages/project/read/index.js, pages/project/read/views/index.jsx
If ASRU have created a ROP for a project then external admin users and project licence holders can then access the ROP.
=> Open access to ROPs to external users

package-lock.json, package.json, pages/project-version/update/js/index.js, pages/project-version/update/router.js, pages/retrospective-assessment/update/js/index.js, pages/retrospective-assessment/update/router.js, pages/rops/procedures/content/index.js, pages/rops/procedures/list/index.js, pages/rops/procedures/list/views/index.jsx
* Updated projects with conditional submit component
* Check can submit ra rop and project, show text if not
=> Feature - collab perms

pages/project/read/index.js, pages/project/read/views/components/retrospective-assessment.jsx
* Read only collabs should not see a link to complete an RA
=> Bugfix - ra perms collab

pages/rops/procedures/list/content/index.js, pages/rops/procedures/list/formatters/index.jsx, pages/rops/procedures/list/schema/index.js
Will also be used in the CSV export of the procedures list.
=> Provide contracted versions of the labels for ROPs list view

pages/rops/update/schema/index.js
* Included condition in customValidate to make sure at least one other species was added for each other{thing}
=> Bugfix - rops other species validation

package-lock.json, package.json, pages/common/content/index.js, pages/profile/permission/views/index.jsx, pages/profile/read/content/index.js, pages/profile/read/views/leave-establishment.jsx, pages/profile/remove/content/index.js, pages/profile/remove/index.js, pages/profile/remove/views/index.jsx
Adds an intermediate confirmation page with a notice about deleting draft applications.
~Note: No further work to be done here, but WIP pending the code in resolver to actually do the deletion of draft applications.~
=> Add new UI for removing permissions from a user

pages/common/assets/sass/pdf/index.scss, pages/project-version/downloads/content/index.js, pages/project-version/middleware/index.js, pages/project-version/nts/content/index.js, pages/project-version/nts/views/components/ra-summary.jsx, pages/project-version/nts/views/index.jsx, pages/project-version/pdf/index.jsx, pages/project-version/pdf/views/nts/nts-pdf.jsx, pages/project/read/views/sections/downloads.jsx
~waiting on https://github.com/UKHomeOffice/asl-projects/pull/741~
=> Allow user to download NTS with draft RA

pages/rops/helpers.js, pages/rops/index.js
The re-use flags are per-species, per-protocol
=> Fix re-use condition in ROPs setup

package-lock.json, package.json, pages/rops/components/cancel-link.jsx, pages/rops/nil-return/views/index.jsx, pages/rops/update/views/index.jsx
* Added back link to rops pages
* bumped components with custom cancel link
=> Feature - rops back link

pages/project/read/content/index.js, pages/project/read/views/components/current-activity.jsx
* Added missing class to inherit tasklist styles
* Added missing countown content
=> bugfix - project task list

pages/task/read/content/project.js, pages/task/read/views/models/project.jsx
* If version discarded, show warning message rather than link to broken task
=> Bugfix - discarded version link

pages/project/formatters/index.jsx
this is a belt-and-braces backstop but the main fix is in the API:
https://github.com/UKHomeOffice/asl-schema/pull/507
=> prevent draft aa showing on non-draft projects

pages/common/routers/form.js, pages/rops/procedures/create/content/index.js, pages/rops/procedures/create/formatters/index.jsx, pages/rops/procedures/create/views/index.jsx, pages/rops/procedures/schema/index.js
~waiting on https://github.com/UKHomeOffice/asl-components/pull/213~
=> Show extra context in reveals for severity options

package-lock.json, package.json, pages/establishment/update/views/index.jsx
And import `uuid` in accordance with recommendations
=> Add missing dependencies

pages/rops/procedures/create/content/index.js, pages/rops/procedures/create/index.js, pages/rops/procedures/create/views/index.jsx, pages/rops/procedures/list/content/index.js, pages/rops/procedures/list/formatters/index.jsx, pages/rops/procedures/list/schema/index.js, pages/rops/procedures/schema/index.js, pages/rops/procedures/update/index.js, pages/rops/update/schema/index.js
* Added special techniques to procedures
* Unset if "no" selected
=> Feature - added special techs to procs

pages/project/read/views/components/start-amendment.jsx, pages/task/content/status.js, pages/task/read/content/project.js, pages/task/read/routers/read.js, pages/task/read/views/models/project.jsx, pages/task/schema/view.js
* updated project read to check latest version is not granted, in order to determine if amendment in place. This allows submitted versions without newer draft to be deleted, or continued
* Added recover button for project tasks where latest version is task version
=> Feature - recover rejected task

pages/task/read/routers/confirm.js, pages/task/read/views/components/ppl-declarations.jsx
* Only save dates if not exempt
* Only render dates if answer to awerb-exempt is no
=> Bugfix - awerb dates

pages/rops/guidance/content/index.js, pages/rops/index.js, pages/rops/update/content/index.js
remove hardcoded occurances of 2021
=> Bugfix - replace year with placeholder

pages/rops/index.js
* GA is showing false when it should be true in some cases. I cannot reproduce, but this line is buggy and I think it may be the culprit
=> Bugfix - rops GA

pages/task/list/router.js
Previously only inspectors and LOs had a "My Tasks" tab, but it's causing confusion as to why some users don't have one. Tasks can be assigned to any ASRU users, so add "My Tasks" for all ASRU users.
=> Show "My Tasks" for all ASRU users

pages/rops/procedures/list/formatters/index.jsx, pages/rops/procedures/schema/index.js, pages/rops/update/schema/index.js, pages/rops/update/views/components/confirm.jsx
* Updated qc other to use multi input
* Updated confirm page and procs
=> Feature - QC other

package-lock.json, package.json, pages/common/assets/sass/style.scss, pages/rops/helpers.js, pages/rops/index.js, pages/rops/procedures/schema/index.js, pages/rops/update/content/index.js, pages/rops/update/formatters/index.jsx, pages/rops/update/schema/index.js, pages/rops/update/views/components/confirm.jsx, pages/rops/update/views/components/regulatory-legislation.jsx, pages/rops/update/views/components/schedule2.jsx, pages/rops/update/views/components/species.jsx, pages/rops/update/views/index.jsx
* Abstracted getSpecies function
* Use this for list of species to see if nhps are included
=> Bugfix - dont include nhps qs if not in rop

pages/common/routers/multi-step.js, pages/rops/update/config.js, pages/rops/update/content/index.js, pages/rops/update/views/components/confirm.jsx
* Updated auto-continue logic to only redirect on submit of confirm page
* Updted button text if there is a redirect step to be completed
=> Feature - redirect to confirm

pages/rops/helpers.js, pages/rops/index.js, pages/rops/update/config.js, pages/rops/update/views/components/confirm.jsx
It was missing before. Now it's not missing.
=> Add schedule 2 species details to ROPs playback

pages/common/assets/sass/style.scss, pages/rops/update/content/index.js, pages/rops/update/formatters/index.jsx
* Updated rops nhps page content as requested
* Added details/summary
=> Content - rops nhps content

pages/project/update-licence-holder/routers/confirm.js, pages/project/update-licence-holder/routers/update.js
* Add collabs to list of profiles a ppl can be transferred to (for basic users)
* Return profile from proj.collabs if found, lookup via api if not
=> Feature - transfer to collab

package-lock.json, package.json, pages/rops/update/content/index.js, pages/rops/update/schema/index.js
* If an option is disabled due to being included in a proc, show a reveal warning
* Bumped components making reveal warning a thing
=> Feature - Rops disabled option warning

package-lock.json, package.json, pages/rops/update/content/index.js, pages/rops/update/schema/index.js
Reverts UKHomeOffice/asl-pages#1321
=> Revert "Feature - Rops disabled option warning"

pages/rops/procedures/create/content/index.js, pages/rops/procedures/create/views/index.jsx
Also hide the section completely if the setup selected no for whether techniques are used.
=> Update content labels for special techniques in procedures form

pages/common/assets/sass/style.scss, pages/profile/list/views/index.jsx, pages/project/list/views/index.jsx, pages/task/list/content/index.js, pages/task/list/router.js, pages/task/list/views/tasklist.jsx
Adds a new "PPL type" filter that becomes available when filtering to just PPL tasks.
Needs https://github.com/UKHomeOffice/asl-components/pull/226
=> Improved tasklist filters

lib/utils/index.js, pages/project-version/update/submit/content/index.js, pages/project-version/update/submit/index.js, pages/project-version/update/submit/schema/index.js, pages/task/read/routers/confirm.js, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/ppl-declarations.jsx
* Updated yes/Yes/no values to boolean in project meta, and task playback
=> Bugfix - boolean project meta

pages/common/routers/form.js
Sometimes fields aren't in schema (pseudo) - dont try and look things up from them
=> Bugfix - form meta

pages/task/read/routers/endorse.js
* This is not being persisted as needs to be taken from the task meta
=> Bugfix - ppl ready question

pages/project-version/pdf/index.jsx, pages/project-version/ppl/index.js
Make everything `Project title (thing)`.
=> Standardise file names for project downloads

pages/rops/update/content/index.js, pages/rops/update/schema/index.js
Needs:
- https://github.com/UKHomeOffice/react-components/pull/61
- https://github.com/UKHomeOffice/asl-components/pull/240
=> Show a warning message when fields cannot be removed

constants/index.js, pages/establishment/rops/components/date-selector.jsx, pages/establishment/rops/overview/content/index.js, pages/establishment/rops/overview/index.js
=> Bugfix - added feature switch to enable 2022 rops

pages/task/list/content/index.js, pages/task/list/views/tasklist.jsx
Needs: 
- https://github.com/UKHomeOffice/asl-workflow/pull/419
=> Add change of licence holder task filter

.eslintignore, enzyme.setup.js, jest.config.js, package-lock.json, package.json, pages/project/read/content/index.js, pages/project/read/index.js, pages/project/read/views/components/rops.jsx, pages/project/read/views/components/rops.spec.jsx
* Updated rops interface to show multiple rops
* Stack previous rops in min form
* Show active rops in large form is this year or unsubmitted
=> Feature - 2022 rops

pages/common/assets/sass/style.scss, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/deadline.jsx, pages/task/read/views/components/task-status.jsx, pages/task/read/views/models/index.jsx, pages/task/read/views/models/project.jsx, pages/task/read/views/models/role.jsx, pages/task/read/views/models/rop.jsx, pages/task/read/views/models/training-pil.jsx
* Added .gutter class to add gutter margin to elements on task page
* Added styling as per designs
=> Tweak - task padding

pages/common/routers/multi-step.js, pages/rops/components/header.jsx, pages/rops/index.js, pages/rops/procedures/create/views/index.jsx, pages/rops/update/content/index.js, pages/rops/update/index.js, pages/rops/update/views/index.jsx
* added step subtitle to rops pages
* added rops header to procs
=> Feature - rops step navigation

package-lock.json, package.json, pages/task/list/views/tasklist.jsx
* Updated asl components with new list filter list component
* Use link filter list to better layout lists of link filters using grid
=> Feature - link filter list

pages/profile/read/views/profile.jsx
While a project is in a draft state then the draft additional availabilities should still be displayed.
=> Show draft additional availability on draft projects

pages/task/read/views/models/place.jsx
When a task contained only named people changes it was super confusing.
=> Show named people changes in place tasks

pages/establishment/rops/index.js
Will fix to be intelligent, but get this out in the meantime.
=> Default ROPs year to 2021

pages/task/list/content/index.js, pages/task/list/views/tasklist.jsx
needs:
- https://github.com/UKHomeOffice/asl-workflow/pull/429
- https://github.com/UKHomeOffice/asl-workflow/pull/430
=> add extra level of filters for PEL tasks

pages/common/routers/related-tasks.js, pages/project/read/views/components/current-activity.jsx, pages/task/list/content/fields.js, pages/task/list/content/index.js, pages/task/list/formatters/index.jsx, pages/task/list/router.js, pages/task/list/schema/index.js
Adds a new column to the ASRU task list and allows it to be sorted.
=> Display active deadline column and allow sorting

pages/establishment/rops/download/index.js
The labels for species as they were input are more meaningful to end users, especially in the case of the Xenopus variants where the key that is stored is actually completely incorrect (but is linked to too much data to reasonably fix forwards).
=> Map species codes to labels in establishment ROP download

pages/common/assets/sass/style.scss, pages/task/content/tasks.js, pages/task/read/content/base.js, pages/task/read/content/place.js, pages/task/read/views/components/task-details.jsx, pages/task/read/views/index.jsx, pages/task/read/views/models/establishment.jsx, pages/task/read/views/models/index.jsx, pages/task/read/views/models/pil.jsx, pages/task/read/views/models/place.jsx, pages/task/read/views/models/project.jsx, pages/task/read/views/models/role.jsx, pages/task/read/views/models/rop.jsx, pages/task/read/views/models/training-pil.jsx
Adds a new section to the top of the task view displaying the most important details for the task.
=> Add new task details section to task pages

pages/retrospective-assessment/update/router.js
If a user has an RA returned by an admin at the endorsement stage then a new version was created, but the old version remained editable.
Check that the version being edited is the current draft version before allowing it to be editable.
=> Stop version of RAs which are not the latest being editable

pages/pil/create/views/index.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4015
=> Add warning to PIL apply to try to prevent dupe applications

lib/utils/index.js, pages/common/content/index.js, pages/project-version/update/endorse/routers/endorse.js, pages/project-version/update/endorse/schema/index.js, pages/task/content/status.js, pages/task/read/content/base.js, pages/task/read/content/reinstate-deadline.js, pages/task/read/content/remove-deadline.js, pages/task/read/index.js, pages/task/read/routers/deadline-reinstate.js, pages/task/read/routers/deadline-remove.js, pages/task/read/routers/index.js, pages/task/read/routes.js, pages/task/read/views/components/activity-log.jsx, pages/task/read/views/components/deadline.jsx, pages/task/read/views/components/ppl-declarations.jsx, pages/task/read/views/reinstate-deadline.jsx, pages/task/read/views/remove-deadline.jsx, pages/task/schema/deadline-reinstate.js, pages/task/schema/deadline-remove.js
The ready answer will now only appear on the declaration if it was completed, and new declarations after the code changes will not display the ready:
=> ASL-3986 - Redesigning how 'complete and correct' works

pages/project/read/views/sections/downloads.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4053
=> Remove PPL template download for legacy projects

pages/success/index.js, pages/success/views/index.jsx
Add link to return to the project after completing a task on a project.
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-3276
=> Add link to the project title on project success page

pages/user/update-password/content/index.js, pages/user/update-password/content/success.js, pages/user/update-password/index.js, pages/user/update-password/views/index.jsx, pages/user/update-password/views/success.jsx
Needs:
- https://github.com/UKHomeOffice/asl-public-api/pull/378
=> Password changes now log the user out

pages/establishment/apply/index.js
When loading the page for applying for a PEL from a draft state need to load the named people.
=> Populate named people on PEL application screen

pages/task/list/components/assign-task.jsx, pages/task/list/formatters/index.jsx, pages/task/list/index.js
Clicking the link assigns the selected task to the currently signed in ASRU user, but does not leave the list view.
=> Add assign to me link in the tasklist

pages/task/read/routers/read.js
ASRU have reported problems loading old tasks for users who have left establishments. Since there is no reason for these tasks not to be visible to ASRU, if the attempt to load the establishment scoped profile fails then fall back to loading the global profile to ensure the task can still load when the user has been removed from the establishment.
=> Allow ASRU to load tasks for users who have left an establishment

pages/pil/read/content/index.js, pages/pil/read/index.js, pages/pil/read/views/index.jsx
The previous description stated that they could not transfer the licence, when they actually can do.
=> Better PIL amend description for ASRU users

pages/task/read/content/pil.js, pages/task/schema/view.js
Resubmitted condition updates on PILs do not go through the NTCO, they go straight to licensing.
=> Fix text on resubmission option for asru users resubmitting PIL conditions.

package-lock.json, package.json, pages/project-version/components/project-status-banner.jsx
WIP - requires asl-components to be merged https://github.com/UKHomeOffice/asl-components/pull/271
=> ASL-4089 - find any suspended establishment from primary or additional

package-lock.json, package.json, pages/project-version/pdf/views/protocols.jsx
This is dependant on https://github.com/UKHomeOffice/asl-projects/pull/861, once that is merged and published the `@asl/projects` version can be updated
=> ASL-4171 - Show details for re-useable step on protocols summary

pages/project-version/nts/schema/legacy.js, pages/project-version/nts/schema/standard.js
Removed apostrophe as per [ASSB-1238](https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1238)
=> ASSB-1238 - Spelling error - NTS

pages/task/read/content/establishment.js, pages/task/read/content/place.js, pages/task/read/content/role.js, pages/task/read/routers/read.js, pages/task/read/views/models/establishment.jsx, pages/task/read/views/models/place.jsx, pages/task/read/views/models/role.jsx
- Add conditions to PEL task pages
- Edit task router to include condition and reminder data
=> Add conditions during PEL amendments

pages/project/read/views/components/rops.jsx, pages/project/read/views/components/rops.spec.jsx
This should fix the issues reported in [ASSB-1243](https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1243) & [ASSB-1244](https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1244)
=> Change to ROPs years displayed on project reporting tab

pages/common/middleware/index.js
Currently when you edit and resubmit a returned task for updating the establishment licence type the task data doesn't copy back to the amendment properly and the NPRC/PELH you added does not automatically populate the field. 
Also the user that is automatically removed by the task is populated in the amendment and when you resubmit they are added back
This automatically populates the correct, updated user and ensures the old user is still removed on resubmission.
=> ASL-4227: Fix bug with edit and resubmit

pages/task/read/routers/confirm.js, pages/task/read/routers/read.js, pages/task/read/views/confirm.jsx
* Added status === "resolved" check to hba forking condition - this means the hba is only shown to internal users as they are about to resolve the task
=> Bugfix - Only show HBA steps when task is being resolved

jest.config.js, pages/task/content/status.js, pages/task/read/content/confirm-hba.js, pages/task/read/content/upload-hba.js, pages/task/read/views/upload-hba.jsx, test/unit/pages/task/read/views/upload-hba.spec.jsx
Following the Harm Benefit Analysis release, ASRU requested a few content changes
=> ASL-4390: HBA post launch updates

pages/task/content/status.js, pages/task/read/content/project.js, test/unit/pages/task/schema/view.spec.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4412
=> [ASL-4412] Only include HBA upload hint for project next steps

package-lock.json, package.json, pages/project-version/middleware/index.js
Reverts https://github.com/UKHomeOffice/asl-pages/pull/1566
=> Revert "Bugfix/assb 1345 without diff window regression"

package-lock.json, package.json, pages/success/content/index.js, pages/task/content/status.js, pages/task/read/content/project.js, pages/task/read/views/components/task-details.jsx
This reverts commit b77a5381e9aaf9badf92f9cb85a62eb96b8c0706.
This needs to be released with other tickets in ASL-4413. Reverting to hold in a branch until all tasks are done.
See also https://github.com/UKHomeOffice/asl-pages/tree/feature/ASL-4419-transfer-hba
=> Revert "[ASL-4419] Transfer HBA - update task screen (#1569)"

package-lock.json, package.json, pages/rops/update/content/index.js, pages/rops/update/schema/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4449
=> [ASL-4449] Update definitions and validation

package-lock.json, package.json
Update dependency asl-components from 13.2.0 to 13.2.1; Update asl-pages from 31.1.1 to 31.1.2
=> Update dependency asl-components from 13.2.0 to 13.2.1

package-lock.json, package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4457
Applies changes from https://github.com/UKHomeOffice/asl-projects/pull/903
=> [ASL-4457] Apply upstream changes

package-lock.json, package.json, pages/project-version/nts/views/components/retrospective-placeholder.jsx
Fix for:
* https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1383
Includes asl-project upstream fixes for:
* https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1393
* https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4507
=> [ASSB-1383]  Fix date issues in downloads

package-lock.json, package.json, pages/task/read/views/confirm.jsx
Includes snippet updates from upstream to make this work as expected if it is an object.
=> ASL-4413 - Restore previous behaviour of trying action as a fallback when it's not an object.

.eslintrc.json, lib/utils/index.js, package-lock.json, package.json
Fixes for ASL-4554, ASL-4533, ASL-4532
Switch to asl-eslint-common
=> Bump asl-projects

package-lock.json, package.json
asl-project updated on NTS and relevant fields. Introduced Modal on checkboxes, improved content and some conditional rendering on NTS fate of animal.
=> dep update, asl-project bump up.

package-lock.json, package.json
fix protocols, asl-project bump up.
=> bump up asl projects for fixes.

.eslintrc.json, package-lock.json, package.json, pages/project-version/nts/schema/standard.js
* Update upstream projects with hint style fix
* Update NTS fate of animals heading to match new wording
* Also QoL change to use renamed eslint config so it works in both places
=> [ASL-4495] PDF fixes

pages/rops/update/content/index.js, pages/rops/update/formatters/index.jsx, pages/rops/update/schema/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4538
=> [ASL-4538] Add forced swim test to RoPs special techniques

pages/rops/helpers.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1387
=> [ASSB-1387] Add tamarins to species list in hasNhps helper.

package-lock.json, package.json
QA defect found on ASSB/1414 fixed asl/pages version bumped up."
=> regression issued on ASSB/1414 fixed asl/pages version bumped up.

package-lock.json, package.json, pages/rops/update/content/index.js, pages/rops/update/formatters/index.jsx
Content modified - In ROPS -> Forced swim test change.
=> forced swim test - name enhanced and hint added. ALL AC matching.

package-lock.json, package.json
* asl-projects
* asl-components
=> [ASSB-1444] Bump upstream versions 

package-lock.json, package.json, pages/project-version/nts/views/components/species-table.jsx
- Ignore species details that are not in "species"
- Handle user entered species that do not have a "value" property
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4639
=> [ASL-4639] Edge cases in NTS PDF species used table

package-lock.json, package.json, pages/project-version/nts/views/components/species-count.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4643
=> [ASL-4643] Handle other species sublists in NTS species count

package-lock.json, package.json, pages/rops/procedures/content/index.js, pages/rops/procedures/create/content/index.js, pages/rops/procedures/list/formatters/index.jsx, pages/rops/procedures/list/schema/index.js, pages/rops/procedures/schema/index.js, pages/rops/procedures/update/index.js, pages/training/modules/content/index.js
asl-4448 remove endangered details
also fixed a typo certificate to certificates in training excemption page
=> asl-4448 remove endangered details

package-lock.json, package.json, pages/profile/read/content/index.js, pages/profile/read/views/profile.jsx
=> feat: [ASL-4594] Named person guides MVP1 - link in person screen

package-lock.json, package.json
failed for unknown reason - https://github.com/UKHomeOffice/asl-pages/pull/1672
- likely this was a local machine issue on the above PR, we should pull back. 
Here: 
- Version update and Dep update.
=> version updated

package-lock.json, package.json, pages/success/index.js
transfered action and resolved status used to determine the correct project Id.
=> hyper link is now correctly pointing to transfered project

package-lock.json, package.json, pages/role/apply/content/index.js, pages/role/apply/schema/index.js, pages/role/apply/views/index.jsx, pages/role/content/named-roles.js, pages/role/named-person-mvp/before-you-apply/content/index.js, pages/role/named-person-mvp/before-you-apply/schema/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4604
=> feat: [ASL-4604] Named person add role page changes

package-lock.json, package.json
=> asl-project upgrade.

package-lock.json, package.json, pages/role/named-person-mvp/before-you-apply/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4700
=> feat: [ASL-4700] Before you nominate page - no button redirect

.drone-1.0.yml, package-lock.json, package.json
=> nodeJs upgrade, CVE update.
